### ISSUE TITLE
请问能否支持tflite fp16量化

### ISSUE THREAD

**Issue by xsong-AI** [alibaba/TinyNeuralNetwork#102]
您好，谷歌官方的tflite转换工具支持直接将tensoflow模型转换为fp16的模型，
https://tensorflow.google.cn/lite/performance/post_training_float16_quant?hl=zh-cn
请问咱们能支持直接将pytorch模型转换为fp16的模型吗？

**Comment by peterjc123** [comment]
@xsong-AI 可以考虑支持一下，貌似只需要把所有float32的buffer变成float16+dequantize的形式即可

**Comment by peterjc123** [comment]
已经在 https://github.com/alibaba/TinyNeuralNetwork/pull/103 中实现了
