### ISSUE TITLE
[converter] support inplace operations

### ISSUE THREAD

**Issue by Raychen0617** [alibaba/TinyNeuralNetwork#105]
Hi, when converting yolov5 PyTorch model from [https://github.com/ultralytics/yolov5](url) to tflite, the output of tflite model does not match when I compare with the original model. This error also greatly affects the predictions of my model. After comparing layer by layer, I found the main error is caused by three reshapes at the Detection (last) part (as the following figure shows). I am wondering is there any way to solve this problem? 
 
![image](https://user-images.githubusercontent.com/46586372/184068539-c8da08b1-218b-47ec-a9f3-f66e1f4e7b72.png)

The code I use to convert 
```
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
dummy_input = torch.rand(1,3,640,640)

for k, m in model.named_modules():
    if isinstance(m, Detect):
        m.inplace = True
        m.onnx_dynamic = True
        m.export = True

convert_and_compare(model,"./checkpoint/test.tflite",  dummy_input)
```

**Comment by peterjc123** [comment]
@Raychen0617 Please use the following script to export your model in TorchScript format and upload that file here.
```py
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
dummy_input = torch.rand(1,3,640,640)
script = torch.jit.trace(model, dummy_input)
torch.jit.save(script, './checkpoint/test.pt')
```
Maybe there are some inplace operations that failed to be correctly translated.

**Comment by Raychen0617** [comment]
Hi, the generated file is here [test.zip](https://github.com/alibaba/TinyNeuralNetwork/files/9307719/test.zip)

I think the error happens at [https://github.com/ultralytics/yolov5/blob/master/models/yolo.py/#L67](url) line 67 ~74
If I comment these lines, the conversion will be correct

**Comment by peterjc123** [comment]
@Raychen0617 Yes, you should set inplace=False as we have very poor support for inplace operators.

**Comment by Raychen0617** [comment]
Ok, thanks a lot, I will close the issue!
