### ISSUE TITLE
TypeError rises up when creating QAT model

### ISSUE THREAD

**Issue by liamsun2019** [alibaba/TinyNeuralNetwork#11]
Hi, a type error happens when I generate the qat model based on a pth model:

TypeError: __init__() got an unexpected keyword argument 'value'

I check the generated the py file re-written by tinynn:
torch.nn.ZeroPad2d(padding=(0, 1, 0, 1), value=0.0)

There are actually codes similar to above line. It's supposed no 'value' is needed for ZeroPad2d. Any suggestions? Thanks a lot and look forward to your help.

**Comment by peterjc123** [comment]
@liamsun2019 Thanks for reporting. Will take a look later.

**Comment by peterjc123** [comment]
The reason is that the `extra_expr` of `torch.nn.ZeroPad2d` is not correctly implemented. I've opened an issue https://github.com/pytorch/pytorch/issues/69205 at the PyTorch side. Meanwhile, we will try to add a workaround in our code generator.

**Comment by peterjc123** [comment]
Should be fixed by https://github.com/alibaba/TinyNeuralNetwork/commit/7a0de9e7d96158acebac8b57a3ff24c36b638b5c and https://github.com/alibaba/TinyNeuralNetwork/commit/6746a8bada045cae4f4bc339bc0380f613637268.

**Comment by liamsun2019** [comment]
Thanks for your quick response and fix. I'll try it out.
