### ISSUE TITLE
Open AI Whisper pytorch model to tflite

### ISSUE THREAD

**Issue by nyadla-sys** [alibaba/TinyNeuralNetwork#121]
@peterjc123 
Could you please help us to convert below tiny english pytorch model to tflite model, Colab notebook would help me alot.
https://openaipublic.azureedge.net/main/whisper/models/d3dd57d32accea0b295c96e26691aa14d8822fac7d9d27d5dc00b4ca2826dd03/tiny.en.pt

Thanks in Advance..

**Comment by peterjc123** [comment]
@nyadla-sys Could you please give me an example input for this model？

**Comment by nyadla-sys** [comment]
https://colab.research.google.com/github/usefulsensors/openai-whisper/blob/main/openai_whisper_ASR.ipynb
refer the below github for more details with input 
https://github.com/usefulsensors/openai-whisper

**Comment by nyadla-sys** [comment]
@peterjc123 The TinyNeuralNetwork tool might be regarded as one of the best in the industry if we could convert this Pytorch model to float32/int8 TFLITE model and if it performs as predicted.

**Comment by nyadla-sys** [comment]
@peterjc123 do you have any update on this ?

**Comment by nyadla-sys** [comment]
@peterjc123  Refer the below colab 
https://colab.research.google.com/github/usefulsensors/openai-whisper/blob/main/tinynn_openai-whisper-ASR-pytorch_to_tflite_int8.ipynb

**Comment by nyadla-sys** [comment]
If i try to enable below line in the above listed colab getting some errors
qat_model = quantizer.quantize()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/tinynn/graph/tracer.py](https://localhost:8080/#) in trace(module, dummy_input, eliminate_dead_graph)
   2678         with construct_trace_graph(module, dummy_input, eliminate_dead_graph) as new_graph:
-> 2679             new_graph.init()
   2680             return new_graph

4 frames
TypeError: forward() missing 1 required positional argument: 'tokens'

During handling of the above exception, another exception occurred:

NameError                                 Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/tinynn/graph/tracer.py](https://localhost:8080/#) in trace(module, dummy_input, eliminate_dead_graph)
   2686             log.error(f'outputs: {[n.unique_name for n in current_graph().output_nodes]}')
   2687             log.error(f'constants: {[n.unique_name for n in current_graph().constant_nodes]}')
-> 2688         quit()

NameError: name 'quit' is not defined

**Comment by nyadla-sys** [comment]
@peterjc123 if you are looking for dataset for the openai whisper asr model.
pls refer the below colab for more details.
https://github.com/voznesenskym/whisper-dynamo/blob/main/notebooks/LibriSpeech.ipynb

**Comment by nyadla-sys** [comment]
@peterjc123 @zhiqwang @zhaoxin111 @xindongzhang ,could you please help anyone of you on this ?

**Comment by peterjc123** [comment]
@nyadla-sys We will take a look soon. We were on a holiday recently.

**Comment by nyadla-sys** [comment]
@peterjc123 Pls refer below colab for more details
https://colab.research.google.com/github/usefulsensors/openai-whisper/blob/main/tinynn_pytorch_to_tflite_int8.ipynb

**Comment by peterjc123** [comment]
> ## If i try to enable below line in the above listed colab getting some errors
> qat_model = quantizer.quantize()
> TypeError Traceback (most recent call last) [/usr/local/lib/python3.7/dist-packages/tinynn/graph/tracer.py](https://localhost:8080/#) in trace(module, dummy_input, eliminate_dead_graph) 2678 with construct_trace_graph(module, dummy_input, eliminate_dead_graph) as new_graph: -> 2679 new_graph.init() 2680 return new_graph
> 
> 4 frames TypeError: forward() missing 1 required positional argument: 'tokens'
> 
> During handling of the above exception, another exception occurred:
> 
> NameError Traceback (most recent call last) [/usr/local/lib/python3.7/dist-packages/tinynn/graph/tracer.py](https://localhost:8080/#) in trace(module, dummy_input, eliminate_dead_graph) 2686 log.error(f'outputs: {[n.unique_name for n in current_graph().output_nodes]}') 2687 log.error(f'constants: {[n.unique_name for n in current_graph().constant_nodes]}') -> 2688 quit()
> 
> NameError: name 'quit' is not defined

This is because you passed in only one input because the model requires two.

As I can see in your notebook, you are trying to export the model separately for ONNX, but with TinyNN you are doing that in a whole, is there a reason for that?

**Comment by nyadla-sys** [comment]
@peterjc123 
If possible, I prefer to create a single, ASR-compatible tflite(int8).
If that's not doable, I'm okay with two tflite(int8) files generated by TinyNN.

**Comment by nyadla-sys** [comment]
@peterjc123 do you plan to support today on this issue ?
is it possible to use tinynn to convert from pytorch to tflite(int8)?
tiny.en.pt

**Comment by peterjc123** [comment]
> @peterjc123 do you plan to support today on this issue ? is it possible to use tinynn to convert from pytorch to tflite(int8)? tiny.en.pt

Let me have a try. I'm not sure I can get this done today. You may to have to wait for a 7-day national holiday for us to come back.

**Comment by peterjc123** [comment]
> @peterjc123 do you plan to support today on this issue ? is it possible to use tinynn to convert from pytorch to tflite(int8)? tiny.en.pt

I'm back but I don't know how to pass the inputs into the model. Would you please post an inline short script for doing that?

**Comment by nyadla-sys** [comment]
@peterjc123 

Refer here for more details 
https://github.com/zhuzilin/whisper-openvino/blob/main/whisper/model.py

**Comment by peterjc123** [comment]
> @peterjc123
> 
> Refer here for more details https://github.com/zhuzilin/whisper-openvino/blob/main/whisper/model.py

Sorry, I need the exact input shapes. For example, given a PyTorch model `m`, and you call `m(x, y)` to get the inference result, I want to know what `x` and `y` is.

**Comment by nyadla-sys** [comment]
@peterjc123 if you could create two models like encode and decode tflite files if that works it is fine

**Comment by nyadla-sys** [comment]
@peterjc123 someone made whisper asr pytotch to custom c/c++ model and it is working as expected
Refer below for more details 
https://github.com/ggerganov/whisper.cpp

**Comment by nyadla-sys** [comment]
@peterjc123 somehow if we make it to convert to  tflite quant int8 model that will be awesome

**Comment by nyadla-sys** [comment]
@peterjc123 Generated single tflite file, pls run the below notebook 
https://colab.research.google.com/github/usefulsensors/openai-whisper/blob/main/tflite_from_huggingface_whisper.ipynb

**Comment by nyadla-sys** [comment]
> > @peterjc123 do you plan to support today on this issue ? is it possible to use tinynn to convert from pytorch to tflite(int8)? tiny.en.pt
> 
> I'm back but I don't know how to pass the inputs into the model. Would you please post an inline short script for doing that?

encoder input shape (1, 80, 3000)
decoder input shape (1, 20)

**Comment by nyadla-sys** [comment]
Refer the below colab link and it generates whisper tflite(int8) model
https://github.com/usefulsensors/openai-whisper/blob/main/tinynn_pytorch_to_tflite_int8.ipynb

**Comment by nyadla-sys** [comment]
@peterjc123 could you please use the below colab and it works to generate hybrid tflite model(weights int8,activations float32) and hoping tinynn could help to generate complete int8 model.
https://colab.research.google.com/github/usefulsensors/openai-whisper/blob/main/notebooks/tflite_from_huggingface_whisper.ipynb

**Comment by peterjc123** [comment]
> @peterjc123 could you please use the below colab and it works to generate hybrid tflite model(weights int8,activations float32) and hoping tinynn could help to generate complete int8 model. https://colab.research.google.com/github/usefulsensors/openai-whisper/blob/main/notebooks/tflite_from_huggingface_whisper.ipynb

It is a Tensorflow model, which we has no support for conversion to TFLite.

**Comment by nyadla-sys** [comment]
@peterjc123 Converted whisper tiny pytorch to tflite model using tinynn, however it is not getting quantized.
https://colab.research.google.com/drive/1IQI_fxSIbvgUt7AILOsKSIJ-MNe10r1P?usp=sharing
Please review and let me know

**Comment by peterjc123** [comment]
@nyadla-sys Looking into it, some of the fully_connected layers are transformed from `torch.matmul`, that is why they are not quantized. Luckily, we have the dynamic quantization interface in TinyNeuralNetwork, which can translate those layers to the quantized kernels. (It will translate the `Conv2d` layers to the quantized kernels too, which is unsupported in native PyTorch)

**Comment by nyadla-sys** [comment]
Feel free to download the openai/whisper-tiny tflite-based Android Whisper ASR APP from [Google App Store](https://play.google.com/store/apps/details?id=com.whisper.android.tflitecpp).

**Comment by peterjc123** [comment]
As this thread is talking about something unrelated to our repo, I'm going to close this one.

**Comment by nyadla-sys** [comment]
@peterjc123  I am still not able to convert pytorch model to quantized  tflite model and I would appreciate your help on this
