### ISSUE TITLE
OneShotChannelPruner fails on Interpolate layer

### ISSUE THREAD

**Issue by anawkward** [alibaba/TinyNeuralNetwork#122]
Hello author. I'm testing some encoder-decoder models here.
After some experiments, it seems that implemented pruner is not working with
interpolate layer.

```
from tinynn.prune import OneShotChannelPruner
import torch
from torch import Tensor
from torch import nn
from torch.nn import functional as F

class Interpolate(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return F.interpolate(x, (24, 24), mode='bilinear', align_corners=False)

class Conv2d_Interpolate(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv2d = nn.Conv2d(3, 24, 3, padding = 1)
        self.interpolate = Interpolate()

    def forward(self, inTensor: Tensor):
        x = self.conv2d(inTensor)
        x = self.interpolate(x)
        return x

model = Conv2d_Interpolate()

dummy_input = torch.rand((1, 3, 192, 192))

_ = model(dummy_input)

pruner = OneShotChannelPruner(model, dummy_input, {"sparsity": {"default" : 0.25}, "metrics": "l2_norm"})
```

running above codes gives error below.
```
INFO (tinynn.graph.modifier) Start tracking tensor dimension changes...
ERROR (tinynn.graph.modifier) error modifier = interpolate_0_f, type = <class 'tinynn.graph.tracer.TraceFunction'>, kind = 
interpolate
...
RuntimeError: The size of tensor a (24) must match the size of tensor b (192) at non-singleton dimension 3
```

oneShotChannelPruner is not currently support interpolate layer?

**Comment by dinghuanghao** [comment]
The interpolate layer is supported, but only Upsampling related interfaces have been released. I will fix it as soon as possible.

**Comment by dinghuanghao** [comment]
Interpolate is already supported and your demo works correctly.

**Comment by anawkward** [comment]
thank you, interpolate layer is now working. could you check this upsampling demo too?


```
from tinynn.prune import OneShotChannelPruner
import torch
from torch import Tensor
from torch import nn
from torch.nn import functional as F
from typing import Optional

class ConvGRU(nn.Module):
    def __init__(self,
                 channels: int,
                 kernel_size: int = 3,
                 padding: int = 1,
                 depthwise_simple: bool = False):
        super().__init__()
        self.channels = channels
        if not depthwise_simple:
            self.ih = nn.Sequential(
                nn.Conv2d(channels * 2, channels * 2, kernel_size, padding=padding),
                nn.Sigmoid()
            )
            self.hh = nn.Sequential(
                nn.Conv2d(channels * 2, channels, kernel_size, padding=padding),
                nn.Tanh()
            )
        else:  # depthwise conv
            self.ih = nn.Sequential(
                nn.Conv2d(channels * 2, channels * 2, kernel_size, groups=channels * 2, padding=padding),
                nn.BatchNorm2d(channels * 2),
                nn.ReLU(inplace=True),
                nn.Conv2d(channels * 2, channels * 2, 1),  # point wise conv
                nn.Hardsigmoid()  # sig vs tanh
            )
            self.hh = nn.Sequential(
                nn.Conv2d(channels * 2, channels * 2, kernel_size, groups=channels * 2, padding=padding),
                nn.BatchNorm2d(channels * 2),
                nn.ReLU(inplace=True),
                nn.Conv2d(channels * 2, channels, 1),
                nn.Hardtanh()
            )

    def forward_single_frame(self, x, h):
        r, z = self.ih(torch.cat([x, h], dim=1)).split(self.channels, dim=1)
        c = self.hh(torch.cat([x, r * h], dim=1))
        h = (1 - z) * h + z * c
        return h, h

    def forward_time_series(self, x, h):
        o = []
        for xt in x.unbind(dim=1):
            ot, h = self.forward_single_frame(xt, h)
            o.append(ot)
        o = torch.stack(o, dim=1)
        return o, h

    def forward(self, x, h: Optional[Tensor]):
        if h is None:
            h = torch.zeros((x.size(0), x.size(-3), x.size(-2), x.size(-1)),
                            device=x.device, dtype=x.dtype)

        if x.ndim == 5:
            return self.forward_time_series(x, h)
        else:
            return self.forward_single_frame(x, h)

class UpsamplingBlock(nn.Module):
    def __init__(self, in_channels, skip_channels, src_channels, out_channels, scale_factor=2, depthwise_simple=False):
        super().__init__()
        self.out_channels = out_channels
        self.scale_factor = scale_factor
        # self.upsample = nn.Upsample(scale_factor=scale_factor, mode='bilinear', align_corners=False)
        if not depthwise_simple:
            self.conv = nn.Sequential(
                nn.Conv2d(in_channels + skip_channels + src_channels, out_channels, 3, 1, 1, bias=False),
                nn.BatchNorm2d(out_channels),
                nn.ReLU(True),
            )
        else:
            self.conv = nn.Sequential(
                nn.Conv2d(in_channels + skip_channels + src_channels,
                          in_channels + skip_channels + src_channels,
                          kernel_size=3,
                          stride=1,
                          padding=1,
                          bias=False,
                          groups=in_channels + skip_channels + src_channels),
                nn.BatchNorm2d(in_channels + skip_channels + src_channels),
                nn.ReLU(True),
                nn.Conv2d(in_channels + skip_channels + src_channels, out_channels, 1, bias=False),
                nn.BatchNorm2d(out_channels),
                nn.ReLU(True),
            )
        self.gru = ConvGRU(out_channels // 2, depthwise_simple=depthwise_simple)

    def forward(self, x, f, s, r: Optional[Tensor]):
        x = F.interpolate(x, s.shape[2:], mode='bilinear', align_corners=False)

        x = torch.cat([x, f, s], dim=1)
        x = self.conv(x)
        a, b = x.split(self.out_channels // 2, dim=1)
        b, r = self.gru(b, r)
        x = torch.cat([a, b], dim=1)
        return x, r

class TestUpsampling(nn.Module):
    def __init__(self):
        super().__init__()
        self.upsample = UpsamplingBlock(128, 40, 3, 80, depthwise_simple=False)
    def forward(self, inTensor):
        # Just reproduce upsampling part with fixed inputs.
        # this taking forever happens in a full model also
        x4, f3, s3, r3 = (torch.randn((1, 128, 12, 12)), torch.randn((1, 40, 24, 24)), torch.randn((1, 3, 24, 24)), None)
        x3, r3 = self.upsample(x4, f3, s3, r3)
        return (x3, r3)

model = TestUpsampling()

dummy_input = torch.randn((1, 3, 192, 192))

_ = model(dummy_input)

pruner = OneShotChannelPruner(model, dummy_input, {"sparsity": {"default" : 0.25}, "metrics": "l2_norm"})
```

my demo loops forever around codes below.

```
while redirect_center not in sub_graphs:
    redirect_center = center_mapping[redirect_center]
```

**Comment by dinghuanghao** [comment]
You can try the official GRU module of PyTorch, we support it, I will take a look at your custom GRU later.

**Comment by anawkward** [comment]
In my experiment, ConvGRU alone works, thanks for looking into it

**Comment by dinghuanghao** [comment]
from tinynn.converter import TFLiteConverter
from tinynn.prune import OneShotChannelPruner
import torch
from torch import Tensor
from torch import nn
from torch.nn import functional as F
from typing import Optional

from tinynn.util.util import import_from_path


class ConvGRU(nn.Module):
    def __init__(self,
                 channels: int,
                 kernel_size: int = 3,
                 padding: int = 1,
                 depthwise_simple: bool = False):
        super().__init__()
        self.channels = channels
        if not depthwise_simple:
            self.ih = nn.Sequential(
                nn.Conv2d(channels * 2, channels * 2, kernel_size, padding=padding),
                nn.Sigmoid()
            )
            self.hh = nn.Sequential(
                nn.Conv2d(channels * 2, channels, kernel_size, padding=padding),
                nn.Tanh()
            )
        else:  # depthwise conv
            self.ih = nn.Sequential(
                nn.Conv2d(channels * 2, channels * 2, kernel_size, groups=channels * 2, padding=padding),
                nn.BatchNorm2d(channels * 2),
                nn.ReLU(inplace=True),
                nn.Conv2d(channels * 2, channels * 2, 1),  # point wise conv
                nn.Hardsigmoid()  # sig vs tanh
            )
            self.hh = nn.Sequential(
                nn.Conv2d(channels * 2, channels * 2, kernel_size, groups=channels * 2, padding=padding),
                nn.BatchNorm2d(channels * 2),
                nn.ReLU(inplace=True),
                nn.Conv2d(channels * 2, channels, 1),
                nn.Hardtanh()
            )

    def forward_single_frame(self, x, h):
        r, z = self.ih(torch.cat([x, h], dim=1)).split(self.channels, dim=1)
        c = self.hh(torch.cat([x, r * h], dim=1))
        h = (1 - z) * h + z * c
        return h, h

    def forward_time_series(self, x, h):
        o = []
        for xt in x.unbind(dim=1):
            ot, h = self.forward_single_frame(xt, h)
            o.append(ot)
        o = torch.stack(o, dim=1)
        return o, h

    def forward(self, x, h: Optional[Tensor]):
        if h is None:
            h = torch.zeros((x.size(0), x.size(-3), x.size(-2), x.size(-1)),
                            device=x.device, dtype=x.dtype)

        if x.ndim == 5:
            return self.forward_time_series(x, h)
        else:
            return self.forward_single_frame(x, h)

class UpsamplingBlock(nn.Module):
    def __init__(self, in_channels, skip_channels, src_channels, out_channels, scale_factor=2, depthwise_simple=False):
        super().__init__()
        self.out_channels = out_channels
        self.scale_factor = scale_factor
        # self.upsample = nn.Upsample(scale_factor=scale_factor, mode='bilinear', align_corners=False)
        if not depthwise_simple:
            self.conv = nn.Sequential(
                nn.Conv2d(in_channels + skip_channels + src_channels, out_channels, 3, 1, 1, bias=False),
                nn.BatchNorm2d(out_channels),
                nn.ReLU(True),
            )
        else:
            self.conv = nn.Sequential(
                nn.Conv2d(in_channels + skip_channels + src_channels,
                          in_channels + skip_channels + src_channels,
                          kernel_size=3,
                          stride=1,
                          padding=1,
                          bias=False,
                          groups=in_channels + skip_channels + src_channels),
                nn.BatchNorm2d(in_channels + skip_channels + src_channels),
                nn.ReLU(True),
                nn.Conv2d(in_channels + skip_channels + src_channels, out_channels, 1, bias=False),
                nn.BatchNorm2d(out_channels),
                nn.ReLU(True),
            )
        self.gru = ConvGRU(out_channels // 2, depthwise_simple=depthwise_simple)

    def forward(self, x, f, s, r: Optional[Tensor]):
        x = F.interpolate(x, s.shape[2:], mode='bilinear', align_corners=False)

        x = torch.cat([x, f, s], dim=1)
        x = self.conv(x)
        a, b = x.split(self.out_channels // 2, dim=1)
        b, r = self.gru(b, r)
        x = torch.cat([a, b], dim=1)
        return x, r

class TestUpsampling(nn.Module):
    def __init__(self):
        super().__init__()
        self.fake_h = nn.Conv2d(40, 40, (1, 1))
        self.upsample = UpsamplingBlock(128, 40, 3, 80, depthwise_simple=False)
        
    def forward(self, x4, f3, s3, r3):
        r3 = self.fake_h(r3)
        x3, r3 = self.upsample(x4, f3, s3, r3)
        return (x3, r3)

model = TestUpsampling()

dummy_input = [torch.ones((1, 128, 12, 12)), torch.ones((1, 40, 24, 24)), torch.ones((1, 3, 24, 24)),  torch.ones((1, 40, 24, 24))]

_ = model(*dummy_input)

pruner = OneShotChannelPruner(model, dummy_input, {"sparsity": {"default" : 0.5}, "metrics": "l2_norm"})
pruner.prune()
pruner.graph.generate_code('out/vit.py', 'out/vit.pth', 'vit')

model = import_from_path('out.vit', "out/vit.py", "vit")()
model.load_state_dict(torch.load("out/vit.pth"))
model.eval()

_ = model(*dummy_input)

**Comment by anawkward** [comment]
Graph tracing works. Now I'm modifying architecture with your advices and working on a channel dimension mismatch between ih and hh layer

**Comment by anawkward** [comment]
While most other dimensional dependencies are traced nicely,
one on a multiplication layer seems not.
```
import torch
from torch import nn
from tinynn.prune import OneShotChannelPruner

class ConvMult(nn.Module):
    def __init__(self,
                 kernel_size: int = 3,
                 padding: int = 1):
        super().__init__()
        self.conv = nn.Conv2d(13, 19, kernel_size, padding)

    def forward(self, a, b):
        conv_out = self.conv(a)
        return conv_out*b # self.conv layer should not be pruned because conv_out will be multiplied by b which has fixed shape

dummy_input = [torch.ones(1,13,24,24), torch.ones(1,19,24,24)]

model = ConvMult()

pruner = OneShotChannelPruner(model, dummy_input, {"sparsity": {"default" : 0.25}, "metrics": "l2_norm"})
pruner.prune()

model(*dummy_input)
```

is it intended behavior?

**Comment by dinghuanghao** [comment]
The main reason is that h is a static variable passed in from outside, not the result of any operator, so we can't know how to prune it. 
Compared with fake conv, you can prune this model in a more reasonable way as follows:
`
import torch
from torch import nn
from tinynn.prune import OneShotChannelPruner


class simplified(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.aspp1 = nn.Conv2d(in_channels, out_channels, 3, padding=1)
        self.aspp2 = nn.Conv2d(in_channels, out_channels, 3, padding=1)
        self.conv1 = nn.Conv2d(out_channels, out_channels, 3, padding=1)
        self.conv2 = nn.Conv2d(out_channels, out_channels // 2, 3, padding=1)

    def forward(self, x, h):
        x = self.aspp1(x) * self.aspp2(x)  # 20
        a, b = x.split(x.shape[1] // 2, dim=1)  #

        if h is None:
            h = b

        c1_out = self.conv1(torch.cat([b, h], dim=1))
        r, z = c1_out.split(c1_out.shape[1] // 2, dim=1)
        c = self.conv2(torch.cat([b, r * h], dim=1))
        b = (1 - z) * h + z * c
        x = torch.cat([a, b], dim=1)
        return x


in_channel = 64
out_channel = 256
hidden_size = out_channel // 2

dummy_input = [torch.ones(1, in_channel, 192, 192), None]

model = simplified(in_channel, out_channel)

model(*dummy_input)

pruner = OneShotChannelPruner(model, dummy_input, {"sparsity": {"default": 0.5}, "metrics": "l2_norm"})
pruner.prune()

new_hidden_dim = model.aspp2.out_channels // 2

dummy_input = [torch.ones(1, in_channel, 192, 192), torch.ones(1, new_hidden_dim, 192, 192)]

model(*dummy_input)

`

**Comment by anawkward** [comment]
well, now I'm getting used to how implemented graph tracing algorithm deals with layer dependencies.
thanks, I'll look more into it
