### ISSUE TITLE
RuntimeError rises up when converting qat model to tflite

### ISSUE THREAD

**Issue by liamsun2019** [alibaba/TinyNeuralNetwork#13]
Hi, my qat training goes well based on your sample code. But the conversion to tflite fails with the following error message:

**RuntimeError: Quantized copy only works with contiguous Tensors**

Based on the core trace, the error comes from:
converter.convert()

My codes are almost the same with the sample code:

print("Start converting the model to TFLite")
with torch.no_grad():
    qat_model.eval()
    qat_model.cpu()

    # The step below converts the model to an actual quantized model, which uses the quantized kernels.
    qat_model = torch.quantization.convert(qat_model)                                                      

    # When converting quantized models to TFLite, please ensure the quantization backend is QNNPACK.
    torch.backends.quantized.engine = 'qnnpack'

    # The code section below is used to convert the model to the TFLite format
    converter = TFLiteConverter(qat_model, dummy_input, tflite_path='out/qat_model.tflite')
    converer.convert()

By the way, I am curious how the trained qat model affect the conversion. Looks like the conversion could be done even without training. Not familiar with that, appreciate your help.Thanks.

**Comment by liamsun2019** [comment]
Detailed error message:
Start converting the model to TFLite
Traceback (most recent call last):
  File "main.py", line 206, in <module>
    main_quant(opt)
  File "main.py", line 197, in main_quant
    converter.convert()
  File "/usr/local/lib/python3.6/dist-packages/TinyNeuralNetwork-0.1.0+3065e301b76398999b4418a3aad8d78c9e651cf6-py3.6.egg/tinynn/converter/base.py", line 260, in convert
    self.init_jit_graph()
  File "/usr/local/lib/python3.6/dist-packages/TinyNeuralNetwork-0.1.0+3065e301b76398999b4418a3aad8d78c9e651cf6-py3.6.egg/tinynn/converter/base.py", line 79, in init_jit_graph
    script = torch.jit.trace(self.model, self.dummy_input)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_trace.py", line 742, in trace
    _module_class,
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_trace.py", line 940, in trace_module
    _force_outplace,
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 725, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 709, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "out/movenet_qat.py", line 164, in forward
    backbone_body_2_conv_1_0 = self.backbone_body_2_conv_1_0(backbone_body_2_conv_0_1)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 725, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 709, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/padding.py", line 21, in forward
    return F.pad(input, self.padding, 'constant', self.value)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 3553, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: Quantized copy only works with contiguous Tensors

**Comment by liamsun2019** [comment]
[movenet_qat.zip](https://github.com/alibaba/TinyNeuralNetwork/files/7646114/movenet_qat.zip)

**Comment by peterjc123** [comment]
@liamsun2019 

> RuntimeError: Quantized copy only works with contiguous Tensors

This seems to be a limitation of quantization. I'm able to workaround this by inserting `.contiguous()` calls of the inputs in the corresponding lines.
e.g. In your traceback, it reports the error on the following line in the model description script.
```py
backbone_body_2_conv_1_0 = self.backbone_body_2_conv_1_0(backbone_body_2_conv_0_1)
````
And, you may change this to the following one.
```py
backbone_body_2_conv_1_0 = self.backbone_body_2_conv_1_0(backbone_body_2_conv_0_1.contiguous())
```
BTW, you'll need to pass some configuration items to the quantizer otherwise it will overwrite your changes.
```
quantizer = QATQuantizer(model, dummy_input, work_dir='out', config={'force_overwrite': False})
```

> By the way, I am curious how the trained qat model affect the conversion. Looks like the conversion could be done even without training. Not familiar with that, appreciate your help.Thanks.

The training phase of the whole QAT process doesn't have an effect on the conversion one. It just fits the weights of your model to adapt the quantization changes, and calculates the min/max ranges so that it may calculate a better scale and offset before you convert it to a quantized model, which leads to better accuracy.

**Comment by peterjc123** [comment]
I also looked into the question that why the error raises. It seems `aten::constant_pad_nd` tries to clone the input when all the pad indices are positive [here](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/ConstantPadNd.cpp#L42) and then it will fail out at [this place](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/quantized/Copy.cpp#L15) since the input is not contiguous. So, what we can do here is to add a pre-trace hook before we call `torch.jit.trace` in `converter.convert`. When the inputs are not contiguous, we make them contiguous.

**Comment by liamsun2019** [comment]
Thanks for your quick feedback.
1. There're a few places that need to add contiguous(). I fixed them one by one and invoke QATQuantizer with 'force_overwrite' set to False. It works and the tflite can be generated as a result.
2. I am not sure how to convert a trained qat model to a tflite version. I actually tried the following method to convert a normal float32 pytorch model to tflite,  based on your sample code:

 model.load_state_dict(torch.load("test.pth"))
 model.cpu()
 model.eval()

 dummy_input = torch.rand((1, 3, 256, 256))

 output_path = os.path.join(mypath, 'test.tflite')
 torch.backends.quantized.engine = 'qnnpack'
 converter = TFLiteConverter(model, dummy_input, output_path)
 converter.convert()

For a certain qat pth model, should I just invoke load_state_dict before the conversion, just like above code lines?

**Comment by liamsun2019** [comment]
I overview the codes of quantizer method in quantizer.py. Looks like that it will load_state_dict from the initial pth and prepare itself for a quantized model. The subsequent training based on the model will update the stuff such as weights/bias internally. Therefore, the following conversion to tflite is just based on the trained qat model. Not sure my understanding correct or not.

**Comment by peterjc123** [comment]
> I overview the codes of quantizer method in quantizer.py. Looks like that it will load_state_dict from the initial pth and prepare itself for a quantized model. The subsequent training based on the model will update the stuff such as weights/bias internally. Therefore, the following conversion to tflite is just based on the trained qat model. Not sure my understanding correct or not.

Yeah, this is correct.

**Comment by liamsun2019** [comment]
Thanks. I finally got the resulted tflite model. But an error rises up reporting:
ValueError: cannot reshape array of size 0 into shape (1,16,16,64)

Looks like the error comes out from ResizeBilinear op.
[error.zip](https://github.com/alibaba/TinyNeuralNetwork/files/7648237/error.zip)

**Comment by liamsun2019** [comment]
This error happens when I use another tool to import the tflite model.

**Comment by peterjc123** [comment]
@liamsun2019 I've inspected the generated model using Netron.
![image](https://user-images.githubusercontent.com/9998726/144702520-4e483442-d0bd-4b37-bc61-e3ad101cf639.png)
As you can see in the graph, we didn't set `new_weight` and `new_height`, but we **did** set the output size as the second input tensor. Since we are targeting the TFLite backend >= 2.3.0, I think the way we currently use is correct and doesn't need a fix. You'll need to update your backend to a more recent version, I guess.

**Comment by liamsun2019** [comment]
Yes, I also think about updating the tflite backend but both tensorflow 2.3.0 and 2.5.0 fail for this model. I'll do further check.

**Comment by peterjc123** [comment]
@liamsun2019 Would you please try to convert the model again using the new codebase? Previously, we convert constant pad with float zero with PADV2, which doesn't work well for quantized models.

**Comment by liamsun2019** [comment]
I upgraded to latest version and the generated tfilte model does not have padv2 op anymore. But the error "ValueError: cannot reshape array of size 0 into shape (1,16,16,64)" still exists. It's supposed not to be related with padv2.
[nopadv2.zip](https://github.com/alibaba/TinyNeuralNetwork/files/7658300/nopadv2.zip)

**Comment by peterjc123** [comment]
I tried to run the the official [benchmark_model](https://www.tensorflow.org/lite/performance/measurement#download_or_build_the_binary) tool with the model you provided and it does return a result. So, I think the model is okay.
```bash
$> ./android_arm_benchmark_model --graph=nopadv2.tflite                                  <
STARTING!
Log parameter values verbosely: [0]
Graph: [nopadv2.tflite]
Loaded model nopadv2.tflite
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
The input model file size (MB): 6.35906
Initialized session in 19.775ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=1 curr=698201

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=50 first=707992 curr=572401 min=569232 max=752566 avg=592279 std=47244

Inference timings in us: Init: 19775, First inference: 698201, Warmup (avg): 698201, Inference (avg): 592279
Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
Memory footprint delta from the start of the tool (MB): init=4.67969 overall=17.3398
```

**Comment by liamsun2019** [comment]
Right, I also tried linux_x86-64_benchmark_model, the result looks also normal. I'll dig into this issue.

**Comment by peterjc123** [comment]
> @liamsun2019
> 
> > RuntimeError: Quantized copy only works with contiguous Tensors
> 
> This seems to be a limitation of quantization. I'm able to workaround this by inserting `.contiguous()` calls of the inputs in the corresponding lines. e.g. In your traceback, it reports the error on the following line in the model description script.
> 
> ```python
> backbone_body_2_conv_1_0 = self.backbone_body_2_conv_1_0(backbone_body_2_conv_0_1)
> ```
> 
> And, you may change this to the following one.
> 
> ```python
> backbone_body_2_conv_1_0 = self.backbone_body_2_conv_1_0(backbone_body_2_conv_0_1.contiguous())
> ```
> 
> BTW, you'll need to pass some configuration items to the quantizer otherwise it will overwrite your changes.
> 
> ```python
> quantizer = QATQuantizer(model, dummy_input, work_dir='out', config={'force_overwrite': False})
> ```
> 
> > By the way, I am curious how the trained qat model affect the conversion. Looks like the conversion could be done even without training. Not familiar with that, appreciate your help.Thanks.
> 
> The training phase of the whole QAT process doesn't have an effect on the conversion one. It just fits the weights of your model to adapt the quantization changes, and calculates the min/max ranges so that it may calculate a better scale and offset before you convert it to a quantized model, which leads to better accuracy.

With https://github.com/alibaba/TinyNeuralNetwork/commit/33c9adbd539357172c2ecbdcf7a47643ae9974c8, you don't need to do that manually. We will handle this case for you.

**Comment by liamsun2019** [comment]
I update to recent version(commit 33c9adb included) and the same error still exists.

**Comment by peterjc123** [comment]
@liamsun2019 I refer to the issue related to quantization, not model conversion.

**Comment by liamsun2019** [comment]
Got it. As for this issue itself, I think it's already resolved and could be closed. Thanks for your help.
