### ISSUE TITLE
Question on conversion accuracy

### ISSUE THREAD

**Issue by Burton2000** [alibaba/TinyNeuralNetwork#152]
Hi there,

I am looking at using TinyNN more as it's a really awesome tool from what I have tried so far. Not an issue but one small question I have is about accuracy of conversion. Is TinyNN designed so that outputs in PyTorch and TFLite are identical?

I can see from here: https://github.com/alibaba/TinyNeuralNetwork/blob/main/tests/converter_test.py#L133 that tests are run against TorchVision models and output compared to a certain tolerance, am I right then that this is the tolerance to use when saying how accurate conversion is?

Thanks,
Richard

**Comment by peterjc123** [comment]
Yes, as you can see [here](https://github.com/alibaba/TinyNeuralNetwork/blob/main/tests/converter_op_test.py), almost every op is tested so for the floating model, it should be within numerical differences.

**Comment by Burton2000** [comment]
Thanks for the quick reply that answers my question.
