### ISSUE TITLE
Weights not shared when static quantizng and converting LSTM

### ISSUE THREAD

**Issue by Burton2000** [alibaba/TinyNeuralNetwork#167]
Hi again,

I was testing quantization and conversion of LSTM models and everything works perfectly for fp32 and dynamic quantization!

However, when doing static quantization (for example with post-training quantization) the model quantizes and converts successfully but the weights are not shared in the model, so the size of the TFLite file is much bigger than it should be. This doesn't happen when converting fp32 models or using dynamic quantization - weights are shared for each step of the LSTM and model size is small as expected. This is all using unroll_lstm=True.

Is there an option that I haven't set correctly or this is just a limitation of conversion at the moment, I couldn't find anything in the documentation?

Many thanks,
Richard

**Comment by peterjc123** [comment]
We will take a look.

**Comment by peterjc123** [comment]
> Is there an option that I haven't set correctly or this is just a limitation of conversion at the moment, I couldn't find anything in the documentation?

Seems to be a bug.  As you can see here, the weight is always created rather than reused. https://github.com/alibaba/TinyNeuralNetwork/blob/main/tinynn/converter/operators/torch/quantized.py#229

**Comment by peterjc123** [comment]
@Burton2000 Actually, this problem is a bit more complicated than I had thought. These weights are generated separated after going through `torch.jit.trace`, so it seems the only way to group them together is to a add `group_weight_pass` in the Graph Optimizer.

**Comment by peterjc123** [comment]
@Burton2000 Added a new option `group_buffers` in TFLiteConverter to mitigate this issue. Please update to the latest version and have a try. https://github.com/alibaba/TinyNeuralNetwork/commit/43295f1521989a7cc05981fe0ca56b6a6271e218#diff-4fdac68b9e814bcddd1a62032f7dc0464582e3c4b740a4d2d80ebbe38d665789R58

**Comment by Burton2000** [comment]
@peterjc123 wow thanks for the quick reply and patch! I have tried it out and seems to be working, the quantized file size is now small again as expected and inference is still working as expected, thank you!

One thing out of curiosity, when inspecting the model in Netron the weight names for the quantized model are still different for each time step which isn't the case for fp32 model. Do you think this is something easy to change so names match if setting `group_buffer_pass=True` or is not worth the time?

**Comment by peterjc123** [comment]
@Burton2000 Well, to achieve that we will need another `group_tensors` pass (or we can just fuse the `group_buffers` pass into the new pass). It should be easy to implement but I don't quite get why we need the same names for weights here. Nevertheless, I can do this anyway.

**Comment by peterjc123** [comment]
@Burton2000 The new option named `group_tensors` is added and should work as what you expected. FYI, the old pass is removed.

**Comment by Burton2000** [comment]
@peterjc123 this is awesome it works perfectly, thank you!
