### ISSUE TITLE
"quantized::instance_norm" Support

### ISSUE THREAD

**Issue by steven0129** [alibaba/TinyNeuralNetwork#17]
Use TFLiteConvert to convert a quantized model containing InstanceNorm2D like below

```python=
converter = TFLiteConverter(model, dummy_input, tflite_path=args.output)
converter.convert()
```

And the error occured like below

```
ERROR (tinynn.converter.base) Unsupported ops: quantized::instance_norm
Traceback (most recent call last):
  File "export/export_model_to_tflite.py", line 131, in <module>
    main()
  File "export/export_model_to_tflite.py", line 117, in main
    converter.convert()
  File "/root/miniconda3/lib/python3.7/site-packages/tinynn/converter/base.py", line 269, in convert
    raise Exception("Cannot continue due to fatal error")
Exception: Cannot continue due to fatal error
```

Look like op "quantized::instance_norm" is unsupported. Could you support "quantized::instance_norm"?
Many Thanks

**Comment by dinghuanghao** [comment]
Tensorflow Lite currently does not support the instance_norm.

**Comment by steven0129** [comment]
Hi @dinghuanghao 

Thanks for fast reply.
Any chances to convert instance_norm to other supported op?

**Comment by peterjc123** [comment]
We may convert the float variant of instance_norm to a bunch of TFLite ops if you want, in which case we will make quantizer skip this op for QAT prepration. FYI, there is no way to translate the quantized one to TFLite.

**Comment by steven0129** [comment]
Converting the float variant of instance_norm to a bunch of TFLite ops looks good to me.

**Comment by peterjc123** [comment]
@steven0129 Implemented, would you please give it a try?

**Comment by steven0129** [comment]
@peterjc123 This patch works. This issue can be closed.
Thanks
