### ISSUE TITLE
The recent version generates incorrect import operations

### ISSUE THREAD

**Issue by liamsun2019** [alibaba/TinyNeuralNetwork#18]
I update to the recent version which supports per-channel QAT. It seems that some incorrect import operations are generated to the model description script, e.g:

import self.float_functional_simple_0
import self.float_functional_simple_1
import self.float_functional_simple_10
import self.float_functional_simple_11
import self.float_functional_simple_12
import self.float_functional_simple_2
import self.float_functional_simple_3
import self.float_functional_simple_4
import self.float_functional_simple_5
import self.float_functional_simple_6
import self.float_functional_simple_7
import self.float_functional_simple_8
import self.float_functional_simple_9

The training then cannot be done due to following error:
   import self.float_functional_simple_0
ModuleNotFoundError: No module named 'self'

**Comment by peterjc123** [comment]
@liamsun2019 Will look into it.

**Comment by liamsun2019** [comment]
The older version does  not have this problem. But I am not sure  from which version this issue is introduced.

**Comment by peterjc123** [comment]
@liamsun2019 Should be fixed. Would you please try again?

**Comment by liamsun2019** [comment]
It works after updating. Thanks for your fast fix.
