### ISSUE TITLE
[converter] Unsupported ops: aten::index_put_

### ISSUE THREAD

**Issue by steven0129** [alibaba/TinyNeuralNetwork#185]
I got the following error: "ERROR (tinynn.converter.base) Unsupported ops: aten::index_put_". Could you support this op?

Many Thanks

**Comment by peterjc123** [comment]
@steven0129 Could you please give me an example that how this aten op is generated?

**Comment by peterjc123** [comment]
This op is generated when you do `a[idx] = b`. We don't support this kind of inplace operations. Please rewrite it using `slice` and `concatenation`s.
