### ISSUE TITLE
ERROR (tinynn.converter.base) Unsupported ops: aten::ScalarImplicit

### ISSUE THREAD

**Issue by weinixuehao** [alibaba/TinyNeuralNetwork#199]
麻烦支持一下这个op

**Comment by peterjc123** [comment]
不是已经支持了吗？
https://github.com/alibaba/TinyNeuralNetwork/blob/main/tinynn/converter/operators/torch/__init__.py#L216

**Comment by peterjc123** [comment]
好吧，大小写错了

**Comment by peterjc123** [comment]
https://github.com/alibaba/TinyNeuralNetwork/commit/8604654358c9966ffa7ab55f2a0d875c6dc1068f
已经支持了

**Comment by weinixuehao** [comment]
谢谢

**Comment by weinixuehao** [comment]
为什么是NoTrackOperator？

**Comment by peterjc123** [comment]
> 为什么是NoTrackOperator？

因为TFLite这边不需要感知这个OP啊，这个OP只是PyTorch/ATen自己用的
