### ISSUE TITLE
transformer compression roadmap

### ISSUE THREAD

**Issue by luohao123** [alibaba/TinyNeuralNetwork#2]
Hi, just wonder if Vit transformer will be supported? Many vision transformer worthy to support such as VIT, Swin-transformer, or some e2e OD like DETR.

Will it plann to support in the future?

**Comment by peterjc123** [comment]
Yes, VIT is one of the first network architectures we will be working on. If things go well, the pruners for these architectures will be ready in about two months.

**Comment by dinghuanghao** [comment]
The pruning of Transformer has been supported, and the example can refer to
[huggingface_vision_transformer(https://github.com/alibaba/TinyNeuralNetwork/blob/main/examples/pruner/oneshot/specific/huggingface_vision_transformer.py)
