### ISSUE TITLE
[converter] unsupported ops

### ISSUE THREAD

**Issue by JustQJ** [alibaba/TinyNeuralNetwork#210]
这些op还不被支持，Unsupported ops: aten::unsafe_chunk, aten::tanh_

**Comment by peterjc123** [comment]
atanh就是加个注册项就好了，unsafe_chunk需要研究下，如果能给个可以产生这个op的例子就好了

**Comment by peterjc123** [comment]
但是要注意我们不支持inplace计算图到非inplace的改写，如果你的代码里面存在inplace修改后继续引用原变量的情况，这种我们是不支持的

**Comment by peterjc123** [comment]
已修复，见 https://github.com/alibaba/TinyNeuralNetwork/commit/760add2a0ac5008022c75c2f05040d379af1b3f1
