### ISSUE TITLE
模型后量化警告

### ISSUE THREAD

**Issue by LUOBO123LUOBO123** [alibaba/TinyNeuralNetwork#214]
1. UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448224956/work/aten/src/ATen/native/BinaryOps.cpp:467.)  result = orig_func(*args, **kwargs)

2.  UserWarning: must run observer before calling calculate_qparams.                                    Returning default scale and zero point 
  Returning default scale and zero point "

3. W TensorImpl.h:1156] Warning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (function operator())
WARNING (tinynn.converter.operators.torch.prim) 520 is of type int64, which is unsupported in TFLite, trying to downcast to int32
WARNING (tinynn.converter.operators.torch.prim) 530 is of type int64, which is unsupported in TFLite, trying to downcast to int32
WARNING (tinynn.converter.operators.torch.prim) 537 is of type int64, which is unsupported in TFLite, trying to downcast to int32

后量化结果不对，可能是什么原因

**Comment by peterjc123** [comment]
这些Warning都不是TinyNN抛出的，不知道提这些的意义是什么
```
UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at /opt/conda/conda-bld/pytorch_1623448224956/work/aten/src/ATen/native/BinaryOps.cpp:467.) result = orig_func(*args, **kwargs)

UserWarning: must run observer before calling calculate_qparams. Returning default scale and zero point
Returning default scale and zero point "

W TensorImpl.h:1156] Warning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (function operator())
```
下面这些Warning虽然是TinyNN报出的，但是把Int64 转成 Int32和精度对不齐一般没有关系
```
WARNING (tinynn.converter.operators.torch.prim) 520 is of type int64, which is unsupported in TFLite, trying to downcast to int32
WARNING (tinynn.converter.operators.torch.prim) 530 is of type int64, which is unsupported in TFLite, trying to downcast to int32
WARNING (tinynn.converter.operators.torch.prim) 537 is of type int64, which is unsupported in TFLite, trying to downcast to int32
```

**Comment by peterjc123** [comment]
先验证 https://github.com/alibaba/TinyNeuralNetwork/blob/main/examples/quantization/post.py#L88 这一步之后的模型精度是否符合要求，如果符合要求，那么再结合 https://github.com/alibaba/TinyNeuralNetwork/blob/main/examples/converter/convert_and_compare.py 这个代码样例验证模型转换器中到底哪一层有问题

**Comment by LUOBO123LUOBO123** [comment]
> 先验证 https://github.com/alibaba/TinyNeuralNetwork/blob/main/examples/quantization/post.py#L88 这一步之后的模型精度是否符合要求，如果符合要求，那么再结合 https://github.com/alibaba/TinyNeuralNetwork/blob/main/examples/converter/convert_and_compare.py 这个代码样例验证模型转换器中到底哪一层有问题

现在的问题就是后量化的模型不对

**Comment by LUOBO123LUOBO123** [comment]
问题已解决，感谢
