### ISSUE TITLE
剪枝問題

### ISSUE THREAD

**Issue by Hank880223** [alibaba/TinyNeuralNetwork#218]
在使用one shot 剪枝時, 模型中若有使用x = torch.nn.functional.pad(x, (0, 1, 0, 1)), 會造成以下的問題
![17995206814642](https://user-images.githubusercontent.com/84907438/232505984-e6997d00-63fb-42bf-97d8-78ce2ef2738c.jpg)

**Comment by peterjc123** [comment]
看起来问题出在这一行，因为你的`F.pad`只提供了两个参数，而他这边应该是按照4个参数写的
https://github.com/alibaba/TinyNeuralNetwork/commit/e77c77380a0c8e6eb21de766beafea483f1f97e5#diff-2269cd0025c06e74bd9dc955e6cf666440614f8ef092e279606444713f5cdb31R1056
所以临时解决方案就是填4个参数 `F.pad(input, (0,1,0,1), 'constant', 0)`

**Comment by dinghuanghao** [comment]
@Hank880223 已修复
