### ISSUE TITLE
Unsupported operator aten::max_pool2d encountered 2 time(s)

### ISSUE THREAD

**Issue by Hairful** [alibaba/TinyNeuralNetwork#219]
When running the sample code, this error happens and the process is killed.
And there is no evaluation.
<img width="1512" alt="Screenshot 2023-04-21 at 12 27 03" src="https://user-images.githubusercontent.com/96092093/233540775-2b39e442-eeac-4118-aa8f-b0200b594f86.png">

**Comment by peterjc123** [comment]
Could you please elaborate a little bit more? Which sample code are you referring to? How is our project involved in your process?

**Comment by Hairful** [comment]
> Could you please elaborate a little bit more? Which sample code are you referring to? How is our project involved in your process?

Sorry about that, after a successful installation, I run
```shell
python federatedscope/main.py --cfg scripts/example_configs/femnist.yaml
```
and encounter that error.

**Comment by peterjc123** [comment]
We don't have the file you mentioned in this repo. I have no idea what you are talking about.

**Comment by Hairful** [comment]
> We don't have the file you mentioned in this repo. I have no idea what you are talking about.

https://federatedscope.io/docs/examples/ I just follow the instructions... 😢

**Comment by peterjc123** [comment]
@Hairful Hey, I don't think our project have anything to do this the website you posted. Maybe you've posted to a wrong place.
