### ISSUE TITLE
Unsupported ops: aten::copy_

### ISSUE THREAD

**Issue by liudatutu** [alibaba/TinyNeuralNetwork#22]
Thanks for your excellent work.  when converting the model from Pytorch to TFLite,it do not supported copy.error follows:
ERROR (tinynn.converter.base) Unsupported ops: aten::copy_
Traceback (most recent call last):
  File "export_tf.py", line 25, in <module>
    converter.convert()
  File "/home/demo/miniconda3/lib/python3.8/site-packages/TinyNeuralNetwork-0.1.0-py3.8.egg/tinynn/converter/base.py", line 269, in convert
    raise Exception("Cannot continue due to fatal error")
Exception: Cannot continue due to fatal error

**Comment by peterjc123** [comment]
@liudatutu Now that https://github.com/alibaba/TinyNeuralNetwork/commit/59dcf8b0767f81d946c3a70f7c540bfb6f21e157 is merged, would you please try again?

**Comment by liudatutu** [comment]
thanks,it is ok now.
