### ISSUE TITLE
Could not export Python function call 'HardSwishJitAutoFn'. 

### ISSUE THREAD

**Issue by weinixuehao** [alibaba/TinyNeuralNetwork#224]
Could not export Python function call 'HardSwishJitAutoFn'. Remove calls to Python functions before export. Did you forget to add @script or @script_method annotation? If this is a nn.ModuleList, add it to __constants__:

**Comment by peterjc123** [comment]
@weinixuehao How is HardSwish implemented in your code?

**Comment by weinixuehao** [comment]
thanks ! it was fixed





------------------ Original ------------------
From: peterjc123 ***@***.***&gt;
Date: Thu,Jun 1,2023 10:46 AM
To: alibaba/TinyNeuralNetwork ***@***.***&gt;
Cc: jackson ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [alibaba/TinyNeuralNetwork] Could not export Python function call'HardSwishJitAutoFn'.  (Issue #224)





 
@weinixuehao How is HardSwish implemented in your code?
