### ISSUE TITLE
模型post量化后转tflite出现如下错误

### ISSUE THREAD

**Issue by pyl62112991** [alibaba/TinyNeuralNetwork#230]
![iwEcAqNwbmcDAQTRBHEFdAawDgJjBJr_ricEds0WdsDfAAfSJKqRoAgACaJpbQoAC9Ew8A png_720x720q90](https://github.com/alibaba/TinyNeuralNetwork/assets/47971541/9d04dd7a-bb42-4219-8e8d-5d8e5e59d72f)

中间模型 jit.save 可以保存，但是不能torch.jit.load

**Comment by peterjc123** [comment]
PyTorch版本？OS？CUDA版本？

**Comment by peterjc123** [comment]
另外这个问题不像是我们这边的问题，应该是PyTorch的问题啊
