### ISSUE TITLE
模型是监督 + 多任务

### ISSUE THREAD

**Issue by weinixuehao** [alibaba/TinyNeuralNetwork#232]
模型是监督 + 多任务 在推理的时候只关心一个输出
模型转换后怎么把不想要的输出删除掉？
或者怎么指定想要的输出？

**Comment by peterjc123** [comment]
https://github.com/alibaba/TinyNeuralNetwork/blob/main/tinynn/converter/base.py#L341 可以在这里根据位置把不要的丢掉 后面我们有空的话提供个接口

**Comment by weinixuehao** [comment]
谢谢
