### ISSUE TITLE
Meet Detailed error: Tensor-likes are not close! using TFLiteConverter

### ISSUE THREAD

**Issue by Juelianqvq** [alibaba/TinyNeuralNetwork#240]
TracerWarning: Output nr 6. of the traced function does not match the corresponding output of the Python function. Detailed error:
Tensor-likes are not close!

Mismatched elements: 255 / 256 (99.6%)
Greatest absolute difference: 0.35748420655727386 at index (0, 0, 11) (up to 1e-05 allowed)
Greatest relative difference: inf at index (0, 0, 175) (up to 1e-05 allowed)
[test_out.zip](https://github.com/alibaba/TinyNeuralNetwork/files/12341111/test_out.zip)

**Comment by peterjc123** [comment]
It seems that the node`input_0_f` is both in the inputs and the outputs of the model. Are you sure you want to do this?
