### ISSUE TITLE
[Converter] Need transpose optimization

### ISSUE THREAD

**Issue by Juelianqvq** [alibaba/TinyNeuralNetwork#242]
[debug.zip](https://github.com/alibaba/TinyNeuralNetwork/files/12366701/debug.zip)
Reproduce:
 input = torch.randn([1, 1, 32, 9, 2])
 converter = TFLiteConverter(model, input)

**Comment by peterjc123** [comment]
Please try using the argument `bypass_elementwise_passthrough_constraint=True` for the TFLiteConverter.
