### ISSUE TITLE
change input to INT8 after converting to tflite

### ISSUE THREAD

**Issue by xyzxinyizhang** [alibaba/TinyNeuralNetwork#264]
I use tinynn converter to convert a quantized pytorch model to tflite. The pytorch model is trained with input in range -0.5-0.5 which is preprocess by (x/255-0.5), while the device can onlly take INT8 as input. If I set the pytorch model input quant scale to 1 and zero point to 0, does the conversion, feed tflite model with input range 0~255, the converted tflite model can not get correct result when feeding tflite model INT8 input. Any step is missing? Thanks for the help!

**Comment by peterjc123** [comment]
https://github.com/alibaba/TinyNeuralNetwork/blob/main/docs/FAQ.md#how-to-fuse-normalization-in-preprocessing-and-the-quantize-op-so-that-the-raw-image-data-is-used-as-input

**Comment by xyzxinyizhang** [comment]
> https://github.com/alibaba/TinyNeuralNetwork/blob/main/docs/FAQ.md#how-to-fuse-normalization-in-preprocessing-and-the-quantize-op-so-that-the-raw-image-data-is-used-as-input

Thank you!
