### ISSUE TITLE
Request: clamp would be more efficient to go to Bounded Relu than Maximum + Minimum

### ISSUE THREAD

**Issue by BmanClark** [alibaba/TinyNeuralNetwork#266]
I was looking at changing the conversion myself, but there isn't a Bounded Relu operator currently, and a whole new operator was a bit too daunting. Bounded Relu won't have the same memory inefficiencies as Maximum/Minimum, is only 1 operator instead of 2, and could be fused with the previous operator if appropriate.
(it's still me looking at the [MI-GAN network](https://github.com/Picsart-AI-Research/MI-GAN) that I provided a pt file for on a previous issue)

**Comment by peterjc123** [comment]
@BmanClark There is no bounded relu op in the builtin operators of TFLite(except Relu6,Relu1 and Relu0_1), as you can see here.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/core/kernels/register.cc

**Comment by peterjc123** [comment]
@BmanClark I guess you need to create a issue for TFLite. Or, if your request is to run on CPU, then you can create a custom op and then you can update the conversion logic to map to that op.

**Comment by BmanClark** [comment]
Ah, indeed, I am looking at ArmNN's op which must be custom. I'll take it up with them... Thank you.
