### ISSUE TITLE
Do not support PReLU module?

### ISSUE THREAD

**Issue by weinixuehao** [alibaba/TinyNeuralNetwork#267]
RuntimeError: Given shapes, [1,128,128,60] and [1,1,40], are not broadcastable.Node number 58 (PRELU) failed to prepare.Failed to apply the default TensorFlow Lite delegate indexed at 0.

**Comment by peterjc123** [comment]
Please provide your PyTorch model.

**Comment by weinixuehao** [comment]
@peterjc123 
Is there any news?

**Comment by peterjc123** [comment]
@weinixuehao I just come back from a long vacation and take a look soon.

**Comment by peterjc123** [comment]
> model.tflite.zip

 Please give me the PyTorch model or the TorchScript model so that I can reproduce the issue.
