### ISSUE TITLE
Conversion to tflite fails for a specific network

### ISSUE THREAD

**Issue by liamsun2019** [alibaba/TinyNeuralNetwork#27]
I applied QAT to a model and the final conversion to tflite fails with the following error messages:

torch.jit._trace.TracingCheckError: Tracing failed sanity checks!
ERROR: Tensor-valued Constant nodes differed in value across invocations. This often indicates that the tracer has encountered untraceable code.
        Node:
                %data_1 : Tensor = prim::Constant[value=<Tensor>]() # out-2022-01-17-08-27-39/detector_qat.py:259:0
        Source Location:
                out-2022-01-17-08-27-39/detector_qat.py(259): forward
                /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py(709): _slow_forward
                /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py(725): _call_impl
                /usr/local/lib/python3.6/dist-packages/torch/jit/_trace.py(940): trace_module
                /usr/local/lib/python3.6/dist-packages/torch/jit/_trace.py(742): trace
                /usr/local/lib/python3.6/dist-packages/TinyNeuralNetwork-0.1.0+e35ef92faba445830bb6156c916b1e838801c07e-py3.6.egg/tinynn/converter/base.py(97): init_jit_graph
                /usr/local/lib/python3.6/dist-packages/TinyNeuralNetwork-0.1.0+e35ef92faba445830bb6156c916b1e838801c07e-py3.6.egg/tinynn/converter/base.py(281): convert
                main.py(133): main
                main.py(193): <module>
        Comparison exception:   promoteTypes with quantized numbers is not handled yet; figure out what the correct rules should be, offending types: QUInt8 Float

Please refer to the attachment. Thanks.
[test.zip](https://github.com/alibaba/TinyNeuralNetwork/files/7878314/test.zip)

**Comment by peterjc123** [comment]
It's a known issue that in some legacy versions of PyTorch, the following code won't be traced.
```py
class Model(nn.Module):
    def forward(self, x):
        // ...
        cat_10 = self.float_functional_simple_9.cat([getitem_15, backbone_stage3_5_branch_main_7], 1)
        data_9 = cat_10.data
        size_9 = data_9.size()
        // ...
```
but it will work when you write like this.
```
```py
class Model(nn.Module):
    def forward(self, x):
        // ...
        cat_10 = self.float_functional_simple_9.cat([getitem_15, backbone_stage3_5_branch_main_7], 1)
        size_9 = cat_10.size()
        // ...
```
We will work on our code generator and tracer to get rid of the `.data` calls.

**Comment by peterjc123** [comment]
@liamsun2019 We pushed a fix for the issue and the given model can be converted locally. Would you please try to remove the existing model description file and try again?

**Comment by liamsun2019** [comment]
Big thanks. I will try it out ASAP.

**Comment by peterjc123** [comment]
I'll close this one for now. If you disagree, please feel free to reopen it.

**Comment by liamsun2019** [comment]
No problem，thanks.

**Comment by liamsun2019** [comment]
The converted tflite model cannot pass benchmark test:
./linux_x86-64_benchmark_model --graph=qat_model.tflite
STARTING!
Log parameter values verbosely: [0]
Graph: [qat_model.tflite]
Loaded model qat_model.tflite
ERROR: tensorflow/lite/kernels/concatenation.cc:179 t->params.scale != output->params.scale (3 != 2018333616)
ERROR: Node number 12 (CONCATENATION) failed to prepare.
Failed to allocate tensors!
Benchmarking failed.

Similar errors happen when doing inference with the tflite model if invoking interpreter.allocate_tensors()

**Comment by peterjc123** [comment]
@liamsun2019 This is because of something else. I've discussed with you through online messages. Next time, please open a new issue for that. Thanks.
