### ISSUE TITLE
PyTorch 转 TFLite 使用 int8 量化

### ISSUE THREAD

**Issue by Tongsen99** [alibaba/TinyNeuralNetwork#274]
converter = TFLiteConverter(
            model,
            dummy_input,
            tflite_path=output_path,
            strict_symmetric_check=True,
            quantize_target_type='int8',
            quantize_input_output_type = 'int8',
            fuse_quant_dequant = True,
        )
中 dummy_input 需要是 int8 类型吗？如果设置了 int8 类型会报 `RuntimeError: expected scalar type Char but found Float`；如果设置了 float32 类型会报 `AssertionError: Unsupported types: input_type: float32, quantize_input_type: int8`。
请问怎样能够解决这个问题，完整实现 PyTorch 转 TFLite 使用 int8 量化（包括输入输出）呢？

**Comment by peterjc123** [comment]
如果需要静态量化（qat或者ptq）请按照examples/quantization下面的样例代码来（你直接把浮点的模型传入TFLiteConverter是不能直接得到静态量化的模型的）,如果是动态量化，参考examples/converter/dynamic.py

**Comment by Tongsen99** [comment]
我使用的就是 examples/converter/dynamic.py 中的代码，然后我换了一个分类模型，希望得到 int8 量化后的 tflite。修改了需要传入的 dummy_input，`dummy_input = torch.ones((1, 3, 64, 64))`，但是设置 dummy_input 为 int8 或 float32 类型都会报错。

**Comment by peterjc123** [comment]
dynamic.py下面还有一系列参数 你没抄全
以及下面这两个参数是给全量化使用的
quantize_input_output_type = 'int8',
fuse_quant_dequant = True,

**Comment by peterjc123** [comment]
> 我使用的就是 examples/converter/dynamic.py 中的代码，然后我换了一个分类模型，希望得到 int8 量化后的 tflite。修改了需要传入的 dummy_input，`dummy_input = torch.ones((1, 3, 64, 64))`，但是设置 dummy_input 为 int8 或 float32 类型都会报错。

你这里int8量化如果是指的全量化模型，你要用examples/quantization下的qat.py或者ptq.py 
关于不同量化技术的比较，可以看tflite的介绍

https://www.tensorflow.org/lite/performance/post_training_quantization?hl=zh-cn

简言之动态量化是weight only量化
静态量化是weight activation都一起量化了
全量化比较快，而且适用于npu等各个芯片
