### ISSUE TITLE
how to do Post-training integer quantization with int16 activation

### ISSUE THREAD

**Issue by FengWu-PKU** [alibaba/TinyNeuralNetwork#279]
模型在int8 PTQ后精度下降很多，请问现在支持int16 activation吗，谢谢

**Comment by FengWu-PKU** [comment]
以及钉钉群的二维码过期吗，能否麻烦更新一下

**Comment by peterjc123** [comment]
> 以及钉钉群的二维码过期吗，能否麻烦更新一下

二维码已经更新了

**Comment by peterjc123** [comment]
> 模型在int8 PTQ后精度下降很多，请问现在支持int16 activation吗，谢谢

Int16量化我们是支持的（详见 https://github.com/alibaba/TinyNeuralNetwork/issues/47 ），但是一般来说后端的实现还不太成熟，可能导致模型推理要比int8慢很多，一般来说还是建议进一步分析是哪些层导致量化的损失，然后在转换时跳过这些层的量化。

**Comment by FengWu-PKU** [comment]
好的，十分感谢
