### ISSUE TITLE
aten::repeat_interleave is considered an unsupported Tensor and causing an error when trying to convert to TFLite

### ISSUE THREAD

**Issue by MariosHavWaller** [alibaba/TinyNeuralNetwork#287]
I've posted about a separate issue that has now been solved on this TinyNN github page before but now I'm experiencing a new issue. So, to reiterate, I'm currently using TinyNN to convert a PyTorch model to TFLite format. Currently this model is able to get converted to ONNX completely fine, but when trying to convert it to TFLite I now run into the error:

```
ERROR (tinynn.converter.base) Unsupported ops: aten::repeat_interleave
Traceback (most recent call last):
  File "c:\Users\marhav01\OneDrive - Arm\Desktop\MobilSAMConverter\PyTorch2TFLiteConv.py", line 67, in <module>
    converter.convert()
  File "C:\Users\marhav01\AppData\Local\Programs\Python\Python311\Lib\site-packages\tinynn\converter\base.py", line 485, in convert
    raise Exception("Cannot continue due to fatal error")
Exception: Cannot continue due to fatal error
```

This is linked to, again, 2 nodes of type aten::repeat_interleave.self_Tensor in the machine learning model (MobileSAMv2) where, in PyTorch format, has a dimension of 0, takes 2 inputs and gives a single output. Is this something that is currently unsupported by TinyNN, and, if so, can it be supported by TinyNN or there a workaround?

This is the conversion code that's been written so far:

```
model = SamOnnxModel(
    model=sam,
    return_single_mask=return_single_mask,
)

embed_dim = sam.prompt_encoder.embed_dim
embed_size = sam.prompt_encoder.image_embedding_size
mask_input_size = [4 * x for x in embed_size]

image_embeddings = torch.randn(1, embed_dim, *embed_size, dtype=torch.float32)
point_coords = torch.randint(low=0, high=1024, size=(1, 5, 2), dtype=torch.int32)
point_labels = torch.randint(low=0, high=4, size=(1, 5), dtype=torch.int32)
mask_input = torch.randn(1, 1, *mask_input_size, dtype=torch.float32)
has_mask_input = torch.tensor([1], dtype=torch.float32)
orig_im_size = torch.tensor([1500, 2250], dtype=torch.float32)

dummy_input_actual = (image_embeddings, point_coords, point_labels, mask_input, has_mask_input, orig_im_size)

name = 'mobileSAM.tflite'
    converter = TFLiteConverter(model, dummy_input_actual, name)
    converter.convert()
```

**Comment by peterjc123** [comment]
It is actually a quite complicated operator to translate. It has the following usages.
For example, we have `x = torch.tensor([[1,2],[3,4]])` and the function signature `torch.repeat_interleave(input, repeats=None, dim=None)`
1. `torch.repeat_interleave(x, 2)`
2. `torch.repeat_interleave(x, torch.tensor([1,2,3,4]))`
3. `torch.repeat_interleave(x, torch.tensor([1,2]), dim=0)`
4. `torch.repeat_interleave(x.flatten())`
They can be split into two very different categories.
1. if repeats is int and dim is None, then it can be translated as `x.reshape(-1,1).repeat(1,repeats).view(-1)`
2. For other cases, we need to transform the `repeats` to `indices` to make the operation like a indexing operation. 
```py
len_repeats = len(repeats) # For `repeats` as an int, it should be the size of the dim
raw_indices = torch.arange(len_repeats)
indices = torch.repeat_interleave(raw_indices, repeats) # This can be calculated by concatenating the tiled raw_indices. e.g. [0] * 1 + [1] * 2 + [2] * 3
```

**Comment by peterjc123** [comment]
Well, I think I will not implement the logic for dynamic `repeats` tensor because it may lead to dynamic-shaped tensors.
