### ISSUE TITLE
convert model error

### ISSUE THREAD

**Issue by YilanWang** [alibaba/TinyNeuralNetwork#292]
我在convert https://github.com/megvii-research/NAFNet 这个模型时, 发现在: https://github.com/megvii-research/NAFNet/blob/2b4af71ebe098a92a75910c233a3965a3e93ede4/basicsr/models/archs/arch_util.py#L291 这里, 会报这样的error: 

`RuntimeError:                                                        
Could not export Python function call 'LayerNormFunction'. Remove calls to Python functions before export. Did you forget to add @script or @script_method annotation? If this is a nn.ModuleList, add it to __constants__:`

请问我要如何解决呢?

**Comment by peterjc123** [comment]
emm，这是因为你的模型没法过`jit.trace`，底层原因是因为你给定的路径下的LayerNorm用了`torch.autograd.Function`来实现，这个需要自己来实现模型的转换映射逻辑。当然还有个简单的方案就是把他给换回普通的`torch.nn.LayerNorm`或者`torch.nn.functional.layer_norm`.
```py
import torch
import torch.nn as nn
import torch.nn.functional as F

def new_layer_norm(self, x):
    normalized_shape = x.shape[1:]
    return F.layer_norm(x, normalized_shape, self.weight.view(-1,1,1).expand(normalized_shape), self.bias.view(-1,1,1).expand(normalized_shape), self.eps)

def patch_layer_norm(model):
    for name, module in parent_module.named_modules():
        if type(module).__name__ == 'LayerNorm2d':
            module.forward = new_layer_norm.get(module, type(module))

patch_layer_norm(model)
```

**Comment by YilanWang** [comment]
确实我发现是trace的问题, 我也打算用pytorch.ln试试, 但是还是不死心想问问能不能支持下这个 :)

**Comment by peterjc123** [comment]
@YilanWang 如果你要走前面那条路也行的，需要实现LayerNormFunction的symbolic方法，参见https://pytorch.org/docs/master/onnx.html#static-symbolic-method

**Comment by peterjc123** [comment]
@YilanWang 结合 #293 应该已经可以了，试下下面的代码
```py
model.eval()
graph = torch.jit.trace(model, dummy_input)

converter = TFLiteConverter(graph, dummy_input, ...)
converter.convert()
```
