### ISSUE TITLE
[PTQ Converter]  'Linear+relu' module conversion failed

### ISSUE THREAD

**Issue by Juelianqvq** [alibaba/TinyNeuralNetwork#300]
You can run 
python post.py 
but it failed to convert fc+relu module.

And if I move relu after dq, the conversion might be done ,however the accuracy may drop down to zero
[a.zip](https://github.com/alibaba/TinyNeuralNetwork/files/15344979/a.zip)

**Comment by peterjc123** [comment]
```py
        transpose_13_f = fake_dequant_inner_81_0_0.transpose(1, 2)
        backbone_encoders_0_dropout_2 = self.backbone_encoders_0_dropout(transpose_13_f)
        add_4_f = add_3_f.__add__(backbone_encoders_0_dropout_2)
        backbone_encoders_0_norm_ff = self.backbone_encoders_0_norm_ff(add_4_f)
        backbone_encoders_0_feed_forward_w_1 = self.backbone_encoders_0_feed_forward_w_1(backbone_encoders_0_norm_ff)
```

```py
  (fake_dequant_inner_81_0_0): DeQuantStub()
  (backbone_encoders_0_norm_ff): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
  (backbone_encoders_0_feed_forward_w_1): LinearReLU(
    (0): Linear(in_features=128, out_features=128, bias=True)
    (1): ReLU()
    (activation_post_process): HistogramObserver(min_val=0.0, max_val=1.3926540613174438)
  )
```

It seems that we should be fuse `backbone_encoders_0_feed_forward_w_1` and ReLU here since they are not quantized.

**Comment by peterjc123** [comment]
Looking into it further, it seems that `backbone_encoders_0_feed_forward_activation` is reused so that it fails in the `is_quantized_analysis` pass.

**Comment by peterjc123** [comment]
@Juelianqvq It seems that https://github.com/alibaba/TinyNeuralNetwork/pull/301 is enough to fix it, though we should probably duplicate those ops in the future.

**Comment by peterjc123** [comment]
@Juelianqvq Let me check how is LinearReLU implemented in PyTorch.

**Comment by peterjc123** [comment]
@Juelianqvq It seems that after model fusing, the original modules involved will be replaced by `nn.Identity`. That's why there's so few ReLUs in the target TFLite model. So it seems we still need to duplicate those activation ops.

**Comment by peterjc123** [comment]
Let's continue the discussion in https://github.com/alibaba/TinyNeuralNetwork/issues/308.
