### ISSUE TITLE
Cannot trace any node

### ISSUE THREAD

**Issue by Kevin-Wei-Chih** [alibaba/TinyNeuralNetwork#33]
Sorry to bother you.

I am just wondering why the tracer cannot trace any of the internal nodes.

I use the torchvision model shown below.
![image](https://user-images.githubusercontent.com/57010307/154434488-9a2a0210-2e4b-4d8e-9ecf-239aa1ceeb95.png)

But got this error.
![image](https://user-images.githubusercontent.com/57010307/154434559-85d88fa9-c7fa-45fa-9d73-c320379c69e1.png)

Do you have any solution to deal with this situation?

Thanks in advance!

**Comment by peterjc123** [comment]
Looks like you are using the nightly version. Sorry for the inconvenience. We will fix it soon.

**Comment by dinghuanghao** [comment]
You can temporarily use PyTorch 1.10.

**Comment by peterjc123** [comment]
Now that the [fix](https://github.com/alibaba/TinyNeuralNetwork/commit/9a79c40cddc605dd50baec32b45e8aa7ce817b52) is landed, would you please try again with a new installation of the library?

**Comment by Kevin-Wei-Chih** [comment]
It works!
I generated the model python file successfully after the 'fix' you provided.
It really helps me a lot.
Thank you very much!
