### ISSUE TITLE
How to remove the Quantize and Dequantize layer on tflite

### ISSUE THREAD

**Issue by Linsop2** [alibaba/TinyNeuralNetwork#373]
![未命名](https://github.com/user-attachments/assets/4e3f7315-6607-45af-be45-631b2b20a432)
![未命名2](https://github.com/user-attachments/assets/f3af2906-89dc-49b3-8c08-341dc15db950)

I want my tflite input to be on uint8 data type (image) and the file is without Quantize and Dequantize
How should I set the QATQuantizer API or other setting?

################ QAT SET #######################
if QAT_train:
    dummy = torch.rand([1,3,224,224])
    quantizer = QATQuantizer(model, dummy, work_dir='out',config={'asymmetric': True, 'per_tensor': False, 'backend':'fbgemm',"rewrite_graph": False})
    model = quantizer.quantize()

    model.qconfig = torch.quantization.get_default_qat_qconfig("fbgemm")
    model = torch.quantization.prepare_qat(model)
    if QAT_pretrain:
        model.load_state_dict(torch.load('./QAT training/epoch_qat.pth'))
        print('load QAT pretrain weight')
##################################

**Comment by peterjc123** [comment]
Please set `fuse_quant_dequant=True` when constructing the `TFLiteConverter` instance.

**Comment by Linsop2** [comment]
> Please set `fuse_quant_dequant=True` when constructing the `TFLiteConverter` instance.

Thank you very much
