### ISSUE TITLE
graph tracer

### ISSUE THREAD

**Issue by www516717402** [alibaba/TinyNeuralNetwork#4]
Why not use torch.FX module and no need a lot of manual work in latest version.

**Comment by peterjc123** [comment]
Good question. There are two major reasons that we write our own graph tracer.
1. When we wrote this code, `torch.fx` was not open source.
2. Currently, `torch.fx` doesn't provide the details of the I/O tensors in the computation graph, thus cannot be used in our pruners.
Once `torch.fx` meets our needs, we can migrate to using it.

**Comment by www516717402** [comment]
@peterjc123 Great project. meanwhile Look forward update FX module to this repo.
