### ISSUE TITLE
Any chance to support int16 quantization for QAT and mixed QAT?

### ISSUE THREAD

**Issue by steven0129** [alibaba/TinyNeuralNetwork#47]
There is a kind of quantization that quantizes model with dynamic fixed point int16. Is there any chance to support int16 quantization for QAT and mixed QAT?

**Comment by peterjc123** [comment]
@steven0129 
First, as far as int16 quantization is concerned, there are generally two tasks we need to finish.
- [ ] Quantizer support
    This is simple. Since PyTorch supports custom quantization ranges, we just need to expose some configuration items to the `Quantizer` type and provide a function to remap the quantization ranges to uint8/int8 ranges.
- [ ] Converter support
    The most difficult part is that we need to recalculate the q-params according to the given n-digits in quantization. Also, I'm not so familiar with int16 quantization in TFLite. So if you could provide one, It would be much appreciated.

Second, what do you mean by mixed QAT? If you refer to mixed FP32 and Int8 computation graph, you can refer to [this example](https://github.com/alibaba/TinyNeuralNetwork/tree/main/examples/mixed_qat).

**Comment by steven0129** [comment]
Hi @peterjc123 

Thanks for fast reply. I have two feedbacks:
1. About converter support, let me study TFLite and find out what I can provide.
2. About mixed QAT, I would like to perform mixed QAT to generate mixed Int16 and [U]Int8 computation graph but not FP32 and [U]Int8 computation graph. Could this be possible?

**Comment by peterjc123** [comment]
@steven0129 Sure, it is possible. But we need to provide int16 quantization support first.

**Comment by steven0129** [comment]
@peterjc123 okay. Got it.

**Comment by peterjc123** [comment]
@steven0129 According to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/conv.cc, it seems that the latest TF only supports the int16 quantization with 16-bit activations and 8-bit weights. Also, it also requires symmetric quantization (zero_point=0).

**Comment by steven0129** [comment]
@peterjc123 The int16 quantization with 16-bit activations and 8-bit weights (16x8 quantization) looks good to me. 
Does symmetric quantization means that TinyNeuralNetwork needs to add symmetric quantiztion support and it would be hard?
Actually, I need depthwise convolution supporting 16x8 quantization too ([https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/depthwise_conv.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/depthwise_conv.cc)) but looks like it only requires affine quantization.

**Comment by peterjc123** [comment]
> The int16 quantization with 16-bit activations and 8-bit weights (16x8 quantization) looks good to me.
> Does symmetric quantization means that TinyNeuralNetwork needs to add symmetric quantiztion support and it would be hard?

No, it is not hard. Just to summarize what I saw from the source code. Actually, it is already supported. But we will need to set custom quant_min, quant_max and implement rescaling in the converter side.







> Actually, I need depthwise convolution supporting 16x8 quantization too (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/depthwise_conv.cc) but looks like it only requires affine quantization.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/depthwise_conv.cc#L136
It requires symmetric quantization as well.

**Comment by steven0129** [comment]
Okay, got it. Many thanks.

**Comment by peterjc123** [comment]
@steven0129 Hi, just want to share some new findings with you. The implementation of int16 support in both quantizer and converter is almost there. But then I find out that most of the int16 kernels in TFLite use reference implementation, which means they may be even slower than float32 ones at this moment. 
Examples:
OPs with reference kernels only: [depthwise_conv](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/depthwise_conv.cc#L441), [fully_connected](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/fully_connected.cc#L759-L765)
OPs with optimized kernels: [conv](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/conv.cc#L820) (currently only in tf_nightly)

**Comment by peterjc123** [comment]
@steven0129 Benchmark (MobileNet V1,Single-threaded,TFLite benchmark-model)
FP32: 229ms
INT16: 2765ms
INT8: 30ms

**Comment by steven0129** [comment]
@peterjc123 Got it! Thanks for your information.

**Comment by peterjc123** [comment]
@steven0129 Related pull request: https://github.com/alibaba/TinyNeuralNetwork/pull/56

**Comment by steven0129** [comment]
Hi @peterjc123 

I tried to merge #56 based on #57 (Merged code is pushed to https://github.com/steven0129/TinyNeuralNetwork/tree/pr/int16_quantization).

Perform below code based on this merged code.

```python
if __name__ == '__main__':
    with model_tracer():
        
        model = QfMobileNet()
        model.eval()
        model.softmax = nn.LogSoftmax(dim=1)
        

        dummy_input = torch.rand((1, 1, 135, 240))
        quantizer = QATQuantizer(
            model, dummy_input, work_dir='test', config={
                'backend': "qnnpack", 
                'force_overwrite': True, 
                'asymmetric': False, 
                'per_tensor': False, 
                'rewrite_graph': True
            }
        )
        qat_model = quantizer.quantize()
        
        device = get_device()
        qat_model.to(device=device)

        context = DLContext()
        context.device = device
        context.max_epoch = 100
        context.criterion = nn.NLLLoss()
        context.optimizer = torch.optim.Adam(qat_model.parameters(), lr=0.001)
        if isinstance(context.criterion, nn.Module):
            context.criterion = context.criterion.to(device=context.device)

        with torch.no_grad():
            qat_model.eval()
            qat_model.cpu()
            qat_model.softmax = nn.Softmax(dim=1)
            qat_model = torch.quantization.convert(qat_model)
            torch.backends.quantized.engine = 'qnnpack'
            converter = TFLiteConverter(qat_model, dummy_input, tflite_path=f'test/resolution_qat.tflite')
            converter.convert()
```

Then I got below error

```
/root/miniconda3/lib/python3.7/site-packages/torch/quantization/observer.py:246: UserWarning: must run observer before calling calculate_qparams.                                        Returning default scale and zero point
  Returning default scale and zero point "
[W TensorImpl.h:1156] Warning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (function operator())
Traceback (most recent call last):
  File "examples/qat/test.py", line 57, in <module>
    converter.convert()
  File "/root/miniconda3/lib/python3.7/site-packages/TinyNeuralNetwork-0.1.0.20220315030537+48aaac0f952e236becef584b4e2a8b3805b412e1-py3.7.egg/tinynn/converter/base.py", line 345, in convert
    self.init_operations()
  File "/root/miniconda3/lib/python3.7/site-packages/TinyNeuralNetwork-0.1.0.20220315030537+48aaac0f952e236becef584b4e2a8b3805b412e1-py3.7.egg/tinynn/converter/base.py", line 310, in init_operations
    converter.parse(node, attrs, args, self.common_graph)
  File "/root/miniconda3/lib/python3.7/site-packages/TinyNeuralNetwork-0.1.0.20220315030537+48aaac0f952e236becef584b4e2a8b3805b412e1-py3.7.egg/tinynn/converter/operators/torch/quantized.py", line 52, in parse
    QuantizedConv2dOperator.parse_common(self, graph_converter, tfl_schema.ActivationFunctionType.RELU)
  File "/root/miniconda3/lib/python3.7/site-packages/TinyNeuralNetwork-0.1.0.20220315030537+48aaac0f952e236becef584b4e2a8b3805b412e1-py3.7.egg/tinynn/converter/operators/torch/quantized.py", line 73, in parse_common
    weight_tensor = self.create_attr_tensor(weight)
  File "/root/miniconda3/lib/python3.7/site-packages/TinyNeuralNetwork-0.1.0.20220315030537+48aaac0f952e236becef584b4e2a8b3805b412e1-py3.7.egg/tinynn/converter/operators/torch/base.py", line 204, in create_attr_tensor
    return tfl.Tensor(tensor, name, has_buffer=True, asymmetric=self.asymmetric, q_type=self.q_type)
  File "/root/miniconda3/lib/python3.7/site-packages/TinyNeuralNetwork-0.1.0.20220315030537+48aaac0f952e236becef584b4e2a8b3805b412e1-py3.7.egg/tinynn/converter/operators/tflite/base.py", line 213, in __init__
    assert tensor.q_zero_point() == asym_s8_offset, (
RuntimeError: Expected quantizer->qscheme() == kPerTensorAffine to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
```

Could you check this problem? Many thanks!

**Comment by steven0129** [comment]
Hi @peterjc123 

I tried to merge #56 based on #57 (Merged code is pushed to https://github.com/steven0129/TinyNeuralNetwork/tree/pr/int16_quantization).

Perform below code based on this merged code.

```python
if __name__ == '__main__':
    with model_tracer():
        
        model = MobileNet()
        model.eval()
        model.softmax = nn.LogSoftmax(dim=1)
        

        dummy_input = torch.rand((1, 1, 135, 240))
        quantizer = QATQuantizer(
            model, dummy_input, work_dir='test', config={
                'backend': "qnnpack", 
                'force_overwrite': True, 
                'asymmetric': False, 
                'per_tensor': False, 
                'rewrite_graph': True
            }
        )
        qat_model = quantizer.quantize()
        
        device = get_device()
        qat_model.to(device=device)

        context = DLContext()
        context.device = device
        context.max_epoch = 100
        context.criterion = nn.NLLLoss()
        context.optimizer = torch.optim.Adam(qat_model.parameters(), lr=0.001)
        if isinstance(context.criterion, nn.Module):
            context.criterion = context.criterion.to(device=context.device)

        with torch.no_grad():
            qat_model.eval()
            qat_model.cpu()
            qat_model.softmax = nn.Softmax(dim=1)
            qat_model = torch.quantization.convert(qat_model)
            torch.backends.quantized.engine = 'qnnpack'
            converter = TFLiteConverter(qat_model, dummy_input, tflite_path=f'test/qat.tflite')
            converter.convert()
```

Then I got below error

```
/root/miniconda3/lib/python3.7/site-packages/torch/quantization/observer.py:246: UserWarning: must run observer before calling calculate_qparams.                                        Returning default scale and zero point
  Returning default scale and zero point "
[W TensorImpl.h:1156] Warning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (function operator())
Traceback (most recent call last):
  File "examples/qat/test.py", line 57, in <module>
    converter.convert()
  File "/root/miniconda3/lib/python3.7/site-packages/TinyNeuralNetwork-0.1.0.20220315030537+48aaac0f952e236becef584b4e2a8b3805b412e1-py3.7.egg/tinynn/converter/base.py", line 345, in convert
    self.init_operations()
  File "/root/miniconda3/lib/python3.7/site-packages/TinyNeuralNetwork-0.1.0.20220315030537+48aaac0f952e236becef584b4e2a8b3805b412e1-py3.7.egg/tinynn/converter/base.py", line 310, in init_operations
    converter.parse(node, attrs, args, self.common_graph)
  File "/root/miniconda3/lib/python3.7/site-packages/TinyNeuralNetwork-0.1.0.20220315030537+48aaac0f952e236becef584b4e2a8b3805b412e1-py3.7.egg/tinynn/converter/operators/torch/quantized.py", line 52, in parse
    QuantizedConv2dOperator.parse_common(self, graph_converter, tfl_schema.ActivationFunctionType.RELU)
  File "/root/miniconda3/lib/python3.7/site-packages/TinyNeuralNetwork-0.1.0.20220315030537+48aaac0f952e236becef584b4e2a8b3805b412e1-py3.7.egg/tinynn/converter/operators/torch/quantized.py", line 73, in parse_common
    weight_tensor = self.create_attr_tensor(weight)
  File "/root/miniconda3/lib/python3.7/site-packages/TinyNeuralNetwork-0.1.0.20220315030537+48aaac0f952e236becef584b4e2a8b3805b412e1-py3.7.egg/tinynn/converter/operators/torch/base.py", line 204, in create_attr_tensor
    return tfl.Tensor(tensor, name, has_buffer=True, asymmetric=self.asymmetric, q_type=self.q_type)
  File "/root/miniconda3/lib/python3.7/site-packages/TinyNeuralNetwork-0.1.0.20220315030537+48aaac0f952e236becef584b4e2a8b3805b412e1-py3.7.egg/tinynn/converter/operators/tflite/base.py", line 213, in __init__
    assert tensor.q_zero_point() == asym_s8_offset, (
RuntimeError: Expected quantizer->qscheme() == kPerTensorAffine to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
```

Could you check this problem? Many thanks!

**Comment by peterjc123** [comment]
@steven0129 You need to pass additional args `quantize_target_type='int16', strict_symmetric_check=True` to the converter object.

**Comment by steven0129** [comment]
Hi @peterjc123 

PR #56 works for me. You can close this issue when #56 is merged.
Many Thanks!
