### ISSUE TITLE
Unsupported ops: argmax, expand, gather

### ISSUE THREAD

**Issue by lee-man** [alibaba/TinyNeuralNetwork#5]
Thanks for your excellent work. It will definitely help when converting the model from Pytorch to TFLite.

When I try to convert the MoveNet (https://github.com/lee-man/movenet-pytorch) to TFLite using tinynn converter, the log reported some unsupported ops: argmax, expand and gather. Hope you can support these ops later:)

**Comment by peterjc123** [comment]
@lee-man Thanks for taking it a shot. We've pushed fixes for `argmax` and `expand`. `gather` is taking us a bit longer, but we will make it available soon.

**Comment by lee-man** [comment]
@peterjc123 Got it. Thanks a lot!

**Comment by peterjc123** [comment]
@lee-man `gather` is supported now. You may have a try.

**Comment by lee-man** [comment]
Got an Error (tinynn/converter/operators/torch/aten.py, line 1568): 
TypeError: create_attr_tensor() got an unexpected keyword argument 'dtype'.

**Comment by peterjc123** [comment]
@lee-man Should be fixed by https://github.com/alibaba/TinyNeuralNetwork/commit/10da5c6345167de8d8b5555881310b660379a4c8. Please try again.

**Comment by lee-man** [comment]
Some problems with the data type for index:
File "/Users/mli/prj/pose/movenet-pytorch/TinyNeuralNetwork/tinynn/converter/base.py", line 256, in convert
    self.init_operations()
  File "/Users/mli/prj/pose/movenet-pytorch/TinyNeuralNetwork/tinynn/converter/base.py", line 226, in init_operations
    converter.parse(node, attrs, args, self.common_graph)
  File "/Users/mli/prj/pose/movenet-pytorch/TinyNeuralNetwork/tinynn/converter/operators/torch/aten.py", line 1661, in parse
    self.run(node)
  File "/Users/mli/prj/pose/movenet-pytorch/TinyNeuralNetwork/tinynn/converter/operators/torch/base.py", line 135, in run
    raise e
  File "/Users/mli/prj/pose/movenet-pytorch/TinyNeuralNetwork/tinynn/converter/operators/torch/base.py", line 129, in run
    o = func(**kwargs)
RuntimeError: gather_out_cpu(): Expected dtype int64 for index

**Comment by lee-man** [comment]
I tried to convert the type manually, and other errors were raised. I think it's due to the complex decoding part of the model I use. I will join the DingTalk group and discuss it with you guys directly. Thanks! @peterjc123

**Comment by peterjc123** [comment]
@lee-man Okay. I managed to fixed the type-related issues.

**Comment by peterjc123** [comment]
@lee-man I've looked into your model. It seems that you tries to call `gather` with the index tensor as a variable, which is unsupported at this time.

**Comment by lee-man** [comment]
@peterjc123 Got it. Really appreciate your help.

**Comment by peterjc123** [comment]
@lee-man I mean this can be fixed. We will do that later.

**Comment by lee-man** [comment]
@peterjc123 Great! Looking forward to your update!

**Comment by peterjc123** [comment]
@lee-man BTW, could you please share the TorchScript model and the shapes of the inputs so that we can look into it easier? Or, maybe we should communicate with each other via DingTalk?

**Comment by peterjc123** [comment]
Now that `gather` should be fully supported. Let's close this issue.
