### ISSUE TITLE
Is dynamic fixed point int16 quantization supported for QAT?

### ISSUE THREAD

**Issue by steven0129** [alibaba/TinyNeuralNetwork#59]
Symmetric int16 quantization is now supported by TinyNN. Any chance support fixed point int16 quantization for QAT?

**Comment by peterjc123** [comment]
@steven0129 Sorry, I didn't quite get what you want.

**Comment by steven0129** [comment]
TFLite seems not to support dynamic fixed point int16. So this issue can be closed.

**Comment by peterjc123** [comment]
@steven0129 Yeah, dynamic int16 quantization is not supported yet in TFLite. Once it is supported, it is really easy to get it supported in TinyNN.

**Comment by steven0129** [comment]
@peterjc123 Got it! Many thanks.
