### ISSUE TITLE
OneShotChannelPruner get error when reshape / view to 3 (or higher) dimension 

### ISSUE THREAD

**Issue by juyenshun** [alibaba/TinyNeuralNetwork#65]
Hi, I got a problem when I use OneShotChannelPruner() to prune my model. I checked the example for mobilenet, it was fine when we use reshape or view like :

x = x.reshape(-1,2049)  or
view_1 = model_14.view(shape_1[0], -1) 

However, when I reshape to higher dimensions like: x = x.reshape(-1, batch_size, 1024), I will get error:
AttributeError: 'TraceNode' object has no attribute 'modifier'
Did I do something wrong? How can I solve the problem? Thanks.

**Comment by peterjc123** [comment]
@dinghuanghao

**Comment by dinghuanghao** [comment]
If possible, please generate model code for me to debug, methods as below: 

`import torch
import torchvision

from tinynn.graph.tracer import model_tracer, trace

with model_tracer():
    model = torchvision.models.alexnet()  # your model
    model.eval()

    dummy_input = torch.rand((1, 3, 224, 224))
    graph = trace(model, dummy_input)
    graph.generate_code('my_alexnet.py', 'my_alexnet.pth', 'Alexnet')`

**Comment by juyenshun** [comment]
Hi,
I wrote a test model to duplicate this problem, and follow the instruction to generate model code. 
However, it seems that the pth file is too large to upload, please run the prune_test.py and generate it. Thanks

[prune_test20220418_1.zip](https://github.com/alibaba/TinyNeuralNetwork/files/8503121/prune_test20220418_1.zip)

**Comment by dinghuanghao** [comment]
1. This issue has been fixed in a patch from the last two weeks.

**Comment by dinghuanghao** [comment]
The latest version already supports reshape, permute, transpose and other operators
