### ISSUE TITLE
bn没有merge进TransposeConv，导致前后插入的fake量化节点

### ISSUE THREAD

**Issue by yaoxinghua** [alibaba/TinyNeuralNetwork#79]
![download](https://user-images.githubusercontent.com/14243376/170631738-356c3c8f-ebff-4f1d-a352-d353b8a5dad9.png)

**Comment by yaoxinghua** [comment]
[coex-share.zip](https://github.com/alibaba/TinyNeuralNetwork/files/8784023/coex-share.zip)
命令：python post_train_quantization.py --netconfig configs/stereo/cfg_coex-crestereo-input640-disp64-costAA2-GW-shenzhenbatch12.yaml

**Comment by peterjc123** [comment]
好吧，直接原因是因为在converter中没有把量化的bn映射成BATCH_NORM算子，所以没有做fusion，其实根本原因是我们不能在converter中直接完成这一步因为这样会导致精度损失。好在1.11的PyTorch已经支持了ConvTranspose和BatchNorm在后量化时的融合，所以可以在量化那边把那些pattern加上，这样可以完成你的需求了。

**Comment by peterjc123** [comment]
相关pr: https://github.com/alibaba/TinyNeuralNetwork/pull/80

**Comment by peterjc123** [comment]
@yaoxinghua 相关改动已合入，升级到PyTorch 1.11应该就可以了

**Comment by yaoxinghua** [comment]
@peterjc123  收到，感谢大佬
