### ISSUE TITLE
QAT LSTM with hidden state (h0, c0) will get error

### ISSUE THREAD

**Issue by juyenshun** [alibaba/TinyNeuralNetwork#83]
Hi,

I want to apply hidden state on my LSTM model and run QAT. The model can run normally without Quantizer, but will get the error below when I apply QATQuantizer:

ERROR (tinynn.graph.tracer) inputs: ['input_1', 'input_2', 'input_3']
ERROR (tinynn.graph.tracer) forwards: []
ERROR (tinynn.graph.tracer) outputs: []
ERROR (tinynn.graph.tracer) constants: []

The attachment is an example file, thanks.
[torch_lstm_test.zip](https://github.com/alibaba/TinyNeuralNetwork/files/8888706/torch_lstm_test.zip)

**Comment by peterjc123** [comment]
Please read the FAQ about exporting LSTM to TFLite. https://github.com/alibaba/TinyNeuralNetwork/blob/main/docs/FAQ.md#how-to-convert-a-model-with-lstm

**Comment by peterjc123** [comment]
FYI, we only support dynamic quantization for the LSTM op. So, with your code, LSTM will still be evaluated with floating type numeric. If you want to mix QAT and dynamic quantization, then you may take a look at https://github.com/alibaba/TinyNeuralNetwork/pull/81.

**Comment by juyenshun** [comment]
Thanks for your information, I will try it!

**Comment by peterjc123** [comment]
This issue will be closed due to inactivity. If you still have problems, please feel free to reopen it. Thanks for your support.
