### ISSUE TITLE
odd size of feature map can cause errors?

### ISSUE THREAD

**Issue by nonononentity** [alibaba/TinyNeuralNetwork#84]
Hello, I use model_convert function to convert .pth from pytorch to .tflite for outside devices. I find different erros in two models. The model1 has several errors in both abs and ref diff, the model2 has only abs diff. 

I doubt whether it is caused by Resize-ops or Odd length of feature map. Model1 has a feature map - 15x43, the model2 has a feature map 15x20. 

1, model 1
First bad error raise up after first resizeNearest's transpose 
![0_nooptim_fastdepth_resizeNearest](https://user-images.githubusercontent.com/72648638/173717050-b60efb23-6826-45e1-aaab-2956b35b1fcd.png)

![2022-06-15 09-35-31屏幕截图](https://user-images.githubusercontent.com/72648638/173717661-c53fbcec-426c-41f4-986a-92b79540f8fb.png)

2, model 2
First bad error raise up before first resizeBilinear's transpose
![0_nooptim_mmpose_resizeBilinear](https://user-images.githubusercontent.com/72648638/173717224-b041ab5a-2a5d-4e93-9e44-d09fc78004e7.png)
![0_nooptim_mmpose_resizeBilnear](https://user-images.githubusercontent.com/72648638/173717234-ec14d0ca-c91a-4938-adde-27fae5e5f111.png)

**Comment by nonononentity** [comment]
233, model 1 has no error just now after I change the feature map size.
And the final res of model is accurate.

![2022-06-15 09-52-41屏幕截图](https://user-images.githubusercontent.com/72648638/173719794-33f22c1f-cfed-4c90-b217-44ffa25de102.png)
![2022-06-15 09-53-07屏幕截图](https://user-images.githubusercontent.com/72648638/173719801-ce2d8b76-af93-417b-8fd5-1d7b0da48b4d.png)

**Comment by peterjc123** [comment]
@nonononentity Would you please share the models in TorchScript format, which can be exported via the following code? Please also tell us the shape of the input tensors.
```py
script = torch.jit.trace(model, dummy_input)
torch.jit.save(script, 'model.pt')
```

**Comment by nonononentity** [comment]
I have changed my builder script, please try my history version. 
[model_1.zip](https://github.com/alibaba/TinyNeuralNetwork/files/8905393/model_1.zip)

This model should be same as "model_1" above, which raise up problems in node 'input0.3' in "NO_OPTIM" tflite file.

**Comment by peterjc123** [comment]
This issue can be reproduced with the following code. We will take a further look soon.
```py
>>> import torch
>>> t = torch.randn(1, 3, 8, 22)
>>> pt = torch.nn.functional.interpolate(t, (15, 43), None, 'nearest')
>>> t_i = t.permute(0, 2,3,1)
>>> import tensorflow as tf
>>> t_o = tf.compat.v1.image.resize_nearest_neighbor(t_i.numpy(), (15, 43), half_pixel_centers=True)
>>> tt = torch.from_numpy(t_o.numpy()).permute(0, 3, 1, 2)
>>> (pt - tt).abs().max()
tensor(5.4481)
>>> (pt - tt).abs().min()
tensor(0.)
>>> torch.nonzero((pt - tt).abs())
tensor([[ 0,  0,  0, 21],
        [ 0,  0,  0, 23],
        [ 0,  0,  0, 25],
        ...,
        [ 0,  2, 14, 37],
        [ 0,  2, 14, 39],
        [ 0,  2, 14, 41]])
```

**Comment by peterjc123** [comment]
@nonononentity Should be fixed via 9e8636a25dc6ab6782fc9441cd7aafbb3fdfa8bc. Would you please try again?

**Comment by nonononentity** [comment]
Thank you. I can't find the details of param `half_pixel-centers` in tensorflow's doc. And I find an old blog which said the calculation of resizeNearest would be same as resizeBilinear when `half_pixel_center=False`.
In fact, I need to resize a feature map used to detect mono depth. The near objects and far objects are separated in distance in groundtruth. So I think resizeNearest maybe better.

I will try it again with resolution (15, 43) feature map after I integrate these bad code. 23333

**Comment by peterjc123** [comment]
Local experiments showed the pr fixed the issue at my side, so I will close the issue for now. If it is not the case, please feel free to reopen it by replying to it.
