### ISSUE TITLE
convert pytorch quantized model to tflite

### ISSUE THREAD

**Issue by touristourist** [alibaba/TinyNeuralNetwork#94]
I have read the tutorial about converting pytorch fp32 model to tflite, but I didn't find how to convert a pytorch int8 model to tflite. Can someone help me? Thanks a lot!

**Comment by peterjc123** [comment]
Please refer to the code examples [here](https://github.com/alibaba/TinyNeuralNetwork/tree/main/examples/quantization#suppored-quantization-methods).
